# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'borrower.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormBorrower(object):
    def setupUi(self, FormBorrower):
        FormBorrower.setObjectName("FormBorrower")
        FormBorrower.resize(1597, 897)
        FormBorrower.setStyleSheet("QMdiSubWindow {background-color : rgb(255, 255, 255) };")
        self.frame_3 = QtWidgets.QFrame(FormBorrower)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 351, 46))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnApplied = QtWidgets.QPushButton(self.frame_3)
        self.btnApplied.setObjectName("btnApplied")
        self.horizontalLayout_6.addWidget(self.btnApplied)
        self.btnEdit = QtWidgets.QPushButton(self.frame_3)
        self.btnEdit.setEnabled(False)
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout_6.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(self.frame_3)
        self.btnDelete.setEnabled(False)
        self.btnDelete.setFlat(False)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_6.addWidget(self.btnDelete)
        self.btnSave = QtWidgets.QPushButton(self.frame_3)
        self.btnSave.setEnabled(False)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_6.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(self.frame_3)
        self.btnCancel.setEnabled(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_6.addWidget(self.btnCancel)
        self.btnFind = QtWidgets.QToolButton(self.frame_3)
        self.btnFind.setEnabled(True)
        self.btnFind.setObjectName("btnFind")
        self.horizontalLayout_6.addWidget(self.btnFind)
        self.layoutWidget = QtWidgets.QWidget(FormBorrower)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 1578, 838))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dockWidgetFindBorrower = QtWidgets.QDockWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetFindBorrower.sizePolicy().hasHeightForWidth())
        self.dockWidgetFindBorrower.setSizePolicy(sizePolicy)
        self.dockWidgetFindBorrower.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidgetFindBorrower.setObjectName("dockWidgetFindBorrower")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_117 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_117.setObjectName("label_117")
        self.verticalLayout_8.addWidget(self.label_117)
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.tableWidget = QtWidgets.QTableWidget(self.dockWidgetContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tableWidget)
        self.dockWidgetFindBorrower.setWidget(self.dockWidgetContents)
        self.horizontalLayout_8.addWidget(self.dockWidgetFindBorrower)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.lblID = QtWidgets.QLabel(self.layoutWidget)
        self.lblID.setObjectName("lblID")
        self.gridLayout_20.addWidget(self.lblID, 0, 0, 1, 1)
        self.lineID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineID.setReadOnly(True)
        self.lineID.setObjectName("lineID")
        self.gridLayout_20.addWidget(self.lineID, 0, 1, 1, 1)
        self.lblDate = QtWidgets.QLabel(self.layoutWidget)
        self.lblDate.setObjectName("lblDate")
        self.gridLayout_20.addWidget(self.lblDate, 1, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setReadOnly(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_20.addWidget(self.dateEdit, 1, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_20)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1028, 769))
        self.tabWidget.setObjectName("tabWidget")
        self.tabBorrower = QtWidgets.QWidget()
        self.tabBorrower.setObjectName("tabBorrower")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabBorrower)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.tabBorrower)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 977, 943))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grpGeneralInfomation = QtWidgets.QGroupBox(self.frame)
        self.grpGeneralInfomation.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpGeneralInfomation.sizePolicy().hasHeightForWidth())
        self.grpGeneralInfomation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grpGeneralInfomation.setFont(font)
        self.grpGeneralInfomation.setObjectName("grpGeneralInfomation")
        self.gridLayout = QtWidgets.QGridLayout(self.grpGeneralInfomation)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.grpGeneralInfomation)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.grpGeneralInfomation)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.grpGeneralInfomation)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.grpGeneralInfomation)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.lineEditFirstName = QtWidgets.QLineEdit(self.grpGeneralInfomation)
        self.lineEditFirstName.setEnabled(True)
        self.lineEditFirstName.setClearButtonEnabled(False)
        self.lineEditFirstName.setObjectName("lineEditFirstName")
        self.gridLayout.addWidget(self.lineEditFirstName, 1, 0, 1, 1)
        self.lineEditMiddleInit = QtWidgets.QLineEdit(self.grpGeneralInfomation)
        self.lineEditMiddleInit.setEnabled(True)
        self.lineEditMiddleInit.setObjectName("lineEditMiddleInit")
        self.gridLayout.addWidget(self.lineEditMiddleInit, 1, 1, 1, 1)
        self.lineEditLastName = QtWidgets.QLineEdit(self.grpGeneralInfomation)
        self.lineEditLastName.setEnabled(True)
        self.lineEditLastName.setObjectName("lineEditLastName")
        self.gridLayout.addWidget(self.lineEditLastName, 1, 2, 1, 1)
        self.lineAlias = QtWidgets.QLineEdit(self.grpGeneralInfomation)
        self.lineAlias.setEnabled(True)
        self.lineAlias.setObjectName("lineAlias")
        self.gridLayout.addWidget(self.lineAlias, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.grpGeneralInfomation)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.grpGeneralInfomation)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.grpGeneralInfomation)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.grpGeneralInfomation)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 3, 1, 1)
        self.cbosex = QtWidgets.QComboBox(self.grpGeneralInfomation)
        self.cbosex.setEnabled(True)
        self.cbosex.setObjectName("cbosex")
        self.cbosex.addItem("")
        self.cbosex.addItem("")
        self.gridLayout.addWidget(self.cbosex, 3, 0, 1, 1)
        self.dateDOB = QtWidgets.QDateEdit(self.grpGeneralInfomation)
        self.dateDOB.setEnabled(True)
        self.dateDOB.setObjectName("dateDOB")
        self.gridLayout.addWidget(self.dateDOB, 3, 1, 1, 1)
        self.cboMaritalStatus = QtWidgets.QComboBox(self.grpGeneralInfomation)
        self.cboMaritalStatus.setEnabled(True)
        self.cboMaritalStatus.setObjectName("cboMaritalStatus")
        self.cboMaritalStatus.addItem("")
        self.cboMaritalStatus.addItem("")
        self.cboMaritalStatus.addItem("")
        self.gridLayout.addWidget(self.cboMaritalStatus, 3, 2, 1, 1)
        self.lineEditTRN = QtWidgets.QLineEdit(self.grpGeneralInfomation)
        self.lineEditTRN.setEnabled(True)
        self.lineEditTRN.setObjectName("lineEditTRN")
        self.gridLayout.addWidget(self.lineEditTRN, 3, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.grpGeneralInfomation)
        self.grpAddress = QtWidgets.QGroupBox(self.frame)
        self.grpAddress.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpAddress.sizePolicy().hasHeightForWidth())
        self.grpAddress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grpAddress.setFont(font)
        self.grpAddress.setObjectName("grpAddress")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grpAddress)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.grpAddress)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.grpAddress)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.grpAddress)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.grpAddress)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 3, 1, 1)
        self.lineAddress1 = QtWidgets.QLineEdit(self.grpAddress)
        self.lineAddress1.setEnabled(True)
        self.lineAddress1.setObjectName("lineAddress1")
        self.gridLayout_2.addWidget(self.lineAddress1, 1, 0, 1, 1)
        self.lineAddress2 = QtWidgets.QLineEdit(self.grpAddress)
        self.lineAddress2.setEnabled(True)
        self.lineAddress2.setObjectName("lineAddress2")
        self.gridLayout_2.addWidget(self.lineAddress2, 1, 1, 1, 1)
        self.lineAddress3 = QtWidgets.QLineEdit(self.grpAddress)
        self.lineAddress3.setEnabled(True)
        self.lineAddress3.setObjectName("lineAddress3")
        self.gridLayout_2.addWidget(self.lineAddress3, 1, 2, 1, 1)
        self.lineLengthOfStay = QtWidgets.QLineEdit(self.grpAddress)
        self.lineLengthOfStay.setEnabled(True)
        self.lineLengthOfStay.setObjectName("lineLengthOfStay")
        self.gridLayout_2.addWidget(self.lineLengthOfStay, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.grpAddress)
        self.grpPrevAddress = QtWidgets.QGroupBox(self.frame)
        self.grpPrevAddress.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpPrevAddress.sizePolicy().hasHeightForWidth())
        self.grpPrevAddress.setSizePolicy(sizePolicy)
        self.grpPrevAddress.setObjectName("grpPrevAddress")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grpPrevAddress)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.grpPrevAddress)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.grpPrevAddress)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.grpPrevAddress)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.grpPrevAddress)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 3, 1, 1)
        self.linePrevAddress1 = QtWidgets.QLineEdit(self.grpPrevAddress)
        self.linePrevAddress1.setEnabled(True)
        self.linePrevAddress1.setObjectName("linePrevAddress1")
        self.gridLayout_3.addWidget(self.linePrevAddress1, 1, 0, 1, 1)
        self.linePrevAddress2 = QtWidgets.QLineEdit(self.grpPrevAddress)
        self.linePrevAddress2.setEnabled(True)
        self.linePrevAddress2.setObjectName("linePrevAddress2")
        self.gridLayout_3.addWidget(self.linePrevAddress2, 1, 1, 1, 1)
        self.linePrevAddress3 = QtWidgets.QLineEdit(self.grpPrevAddress)
        self.linePrevAddress3.setEnabled(True)
        self.linePrevAddress3.setObjectName("linePrevAddress3")
        self.gridLayout_3.addWidget(self.linePrevAddress3, 1, 2, 1, 1)
        self.linePrevLengthOfStay = QtWidgets.QLineEdit(self.grpPrevAddress)
        self.linePrevLengthOfStay.setEnabled(True)
        self.linePrevLengthOfStay.setObjectName("linePrevLengthOfStay")
        self.gridLayout_3.addWidget(self.linePrevLengthOfStay, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.grpPrevAddress)
        self.grpContacts = QtWidgets.QGroupBox(self.frame)
        self.grpContacts.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpContacts.sizePolicy().hasHeightForWidth())
        self.grpContacts.setSizePolicy(sizePolicy)
        self.grpContacts.setObjectName("grpContacts")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.grpContacts)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_21 = QtWidgets.QLabel(self.grpContacts)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.grpContacts)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.grpContacts)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.grpContacts)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 3, 1, 1)
        self.lineHomeTel = QtWidgets.QLineEdit(self.grpContacts)
        self.lineHomeTel.setEnabled(True)
        self.lineHomeTel.setObjectName("lineHomeTel")
        self.gridLayout_4.addWidget(self.lineHomeTel, 1, 0, 1, 1)
        self.lineWorkTel = QtWidgets.QLineEdit(self.grpContacts)
        self.lineWorkTel.setEnabled(True)
        self.lineWorkTel.setObjectName("lineWorkTel")
        self.gridLayout_4.addWidget(self.lineWorkTel, 1, 1, 1, 1)
        self.lineCellNo1 = QtWidgets.QLineEdit(self.grpContacts)
        self.lineCellNo1.setEnabled(True)
        self.lineCellNo1.setObjectName("lineCellNo1")
        self.gridLayout_4.addWidget(self.lineCellNo1, 1, 2, 1, 1)
        self.lineCellNo2 = QtWidgets.QLineEdit(self.grpContacts)
        self.lineCellNo2.setEnabled(True)
        self.lineCellNo2.setObjectName("lineCellNo2")
        self.gridLayout_4.addWidget(self.lineCellNo2, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.grpContacts)
        self.grpPrevEmployment = QtWidgets.QGroupBox(self.frame)
        self.grpPrevEmployment.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpPrevEmployment.sizePolicy().hasHeightForWidth())
        self.grpPrevEmployment.setSizePolicy(sizePolicy)
        self.grpPrevEmployment.setObjectName("grpPrevEmployment")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.grpPrevEmployment)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_25 = QtWidgets.QLabel(self.grpPrevEmployment)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.grpPrevEmployment)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.grpPrevEmployment)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 0, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.grpPrevEmployment)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 0, 3, 1, 1)
        self.linePrevEmployer = QtWidgets.QLineEdit(self.grpPrevEmployment)
        self.linePrevEmployer.setEnabled(True)
        self.linePrevEmployer.setText("")
        self.linePrevEmployer.setObjectName("linePrevEmployer")
        self.gridLayout_5.addWidget(self.linePrevEmployer, 1, 0, 1, 1)
        self.linePrevOccupation = QtWidgets.QLineEdit(self.grpPrevEmployment)
        self.linePrevOccupation.setEnabled(True)
        self.linePrevOccupation.setText("")
        self.linePrevOccupation.setObjectName("linePrevOccupation")
        self.gridLayout_5.addWidget(self.linePrevOccupation, 1, 1, 1, 1)
        self.datePrevEmpStartDate = QtWidgets.QDateEdit(self.grpPrevEmployment)
        self.datePrevEmpStartDate.setEnabled(True)
        self.datePrevEmpStartDate.setObjectName("datePrevEmpStartDate")
        self.gridLayout_5.addWidget(self.datePrevEmpStartDate, 1, 2, 1, 1)
        self.linePrevDepartment = QtWidgets.QLineEdit(self.grpPrevEmployment)
        self.linePrevDepartment.setEnabled(True)
        self.linePrevDepartment.setText("")
        self.linePrevDepartment.setObjectName("linePrevDepartment")
        self.gridLayout_5.addWidget(self.linePrevDepartment, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.grpPrevEmployment)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.grpPrevEmployment)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.grpPrevEmployment)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 2, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.grpPrevEmployment)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 2, 3, 1, 1)
        self.linePrevEmpAddress1 = QtWidgets.QLineEdit(self.grpPrevEmployment)
        self.linePrevEmpAddress1.setEnabled(True)
        self.linePrevEmpAddress1.setText("")
        self.linePrevEmpAddress1.setObjectName("linePrevEmpAddress1")
        self.gridLayout_5.addWidget(self.linePrevEmpAddress1, 3, 0, 1, 1)
        self.linePrevEmpAddress2 = QtWidgets.QLineEdit(self.grpPrevEmployment)
        self.linePrevEmpAddress2.setEnabled(True)
        self.linePrevEmpAddress2.setText("")
        self.linePrevEmpAddress2.setObjectName("linePrevEmpAddress2")
        self.gridLayout_5.addWidget(self.linePrevEmpAddress2, 3, 1, 1, 1)
        self.linePrevEmpAddress3 = QtWidgets.QLineEdit(self.grpPrevEmployment)
        self.linePrevEmpAddress3.setEnabled(True)
        self.linePrevEmpAddress3.setText("")
        self.linePrevEmpAddress3.setObjectName("linePrevEmpAddress3")
        self.gridLayout_5.addWidget(self.linePrevEmpAddress3, 3, 2, 1, 1)
        self.linePrevEmpTelNo = QtWidgets.QLineEdit(self.grpPrevEmployment)
        self.linePrevEmpTelNo.setEnabled(True)
        self.linePrevEmpTelNo.setText("")
        self.linePrevEmpTelNo.setObjectName("linePrevEmpTelNo")
        self.gridLayout_5.addWidget(self.linePrevEmpTelNo, 3, 3, 1, 1)
        self.label_25.raise_()
        self.label_27.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.linePrevOccupation.raise_()
        self.datePrevEmpStartDate.raise_()
        self.linePrevDepartment.raise_()
        self.label_26.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.linePrevEmpAddress1.raise_()
        self.linePrevEmpAddress2.raise_()
        self.linePrevEmpAddress3.raise_()
        self.linePrevEmpTelNo.raise_()
        self.linePrevEmployer.raise_()
        self.verticalLayout_2.addWidget(self.grpPrevEmployment)
        self.grpEmployment = QtWidgets.QGroupBox(self.frame)
        self.grpEmployment.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpEmployment.sizePolicy().hasHeightForWidth())
        self.grpEmployment.setSizePolicy(sizePolicy)
        self.grpEmployment.setObjectName("grpEmployment")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.grpEmployment)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_37 = QtWidgets.QLabel(self.grpEmployment)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 2, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.grpEmployment)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 2, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.grpEmployment)
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 2, 3, 1, 1)
        self.lineEmpAddress1 = QtWidgets.QLineEdit(self.grpEmployment)
        self.lineEmpAddress1.setEnabled(True)
        self.lineEmpAddress1.setText("")
        self.lineEmpAddress1.setObjectName("lineEmpAddress1")
        self.gridLayout_6.addWidget(self.lineEmpAddress1, 3, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.grpEmployment)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 2, 1, 1, 1)
        self.lineEmpTelNo = QtWidgets.QLineEdit(self.grpEmployment)
        self.lineEmpTelNo.setEnabled(True)
        self.lineEmpTelNo.setText("")
        self.lineEmpTelNo.setObjectName("lineEmpTelNo")
        self.gridLayout_6.addWidget(self.lineEmpTelNo, 3, 3, 1, 1)
        self.lineEmpAddress2 = QtWidgets.QLineEdit(self.grpEmployment)
        self.lineEmpAddress2.setEnabled(True)
        self.lineEmpAddress2.setText("")
        self.lineEmpAddress2.setObjectName("lineEmpAddress2")
        self.gridLayout_6.addWidget(self.lineEmpAddress2, 3, 1, 1, 1)
        self.lineEmpAddress3 = QtWidgets.QLineEdit(self.grpEmployment)
        self.lineEmpAddress3.setEnabled(True)
        self.lineEmpAddress3.setText("")
        self.lineEmpAddress3.setObjectName("lineEmpAddress3")
        self.gridLayout_6.addWidget(self.lineEmpAddress3, 3, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.grpEmployment)
        self.label_49.setObjectName("label_49")
        self.gridLayout_6.addWidget(self.label_49, 4, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.grpEmployment)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 0, 0, 1, 1)
        self.lineEmployer = QtWidgets.QLineEdit(self.grpEmployment)
        self.lineEmployer.setEnabled(True)
        self.lineEmployer.setText("")
        self.lineEmployer.setObjectName("lineEmployer")
        self.gridLayout_6.addWidget(self.lineEmployer, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.grpEmployment)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.grpEmployment)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 0, 2, 1, 1)
        self.lineOccupation = QtWidgets.QLineEdit(self.grpEmployment)
        self.lineOccupation.setEnabled(True)
        self.lineOccupation.setText("")
        self.lineOccupation.setObjectName("lineOccupation")
        self.gridLayout_6.addWidget(self.lineOccupation, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.grpEmployment)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 0, 3, 1, 1)
        self.dateEmpStartDate = QtWidgets.QDateEdit(self.grpEmployment)
        self.dateEmpStartDate.setEnabled(True)
        self.dateEmpStartDate.setObjectName("dateEmpStartDate")
        self.gridLayout_6.addWidget(self.dateEmpStartDate, 1, 2, 1, 1)
        self.lineDepartment = QtWidgets.QLineEdit(self.grpEmployment)
        self.lineDepartment.setEnabled(True)
        self.lineDepartment.setText("")
        self.lineDepartment.setObjectName("lineDepartment")
        self.gridLayout_6.addWidget(self.lineDepartment, 1, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.grpEmployment)
        self.label_50.setObjectName("label_50")
        self.gridLayout_6.addWidget(self.label_50, 4, 1, 1, 1)
        self.lineEditSalaryAmount = QtWidgets.QLineEdit(self.grpEmployment)
        self.lineEditSalaryAmount.setEnabled(True)
        self.lineEditSalaryAmount.setObjectName("lineEditSalaryAmount")
        self.gridLayout_6.addWidget(self.lineEditSalaryAmount, 5, 1, 1, 1)
        self.cboPaymentPeriod = QtWidgets.QComboBox(self.grpEmployment)
        self.cboPaymentPeriod.setEnabled(True)
        self.cboPaymentPeriod.setObjectName("cboPaymentPeriod")
        self.cboPaymentPeriod.addItem("")
        self.cboPaymentPeriod.addItem("")
        self.cboPaymentPeriod.addItem("")
        self.cboPaymentPeriod.addItem("")
        self.gridLayout_6.addWidget(self.cboPaymentPeriod, 5, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.grpEmployment)
        self.grpspouse = QtWidgets.QGroupBox(self.frame)
        self.grpspouse.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpspouse.sizePolicy().hasHeightForWidth())
        self.grpspouse.setSizePolicy(sizePolicy)
        self.grpspouse.setObjectName("grpspouse")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.grpspouse)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_41 = QtWidgets.QLabel(self.grpspouse)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.grpspouse)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.grpspouse)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 0, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.grpspouse)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 0, 3, 1, 1)
        self.lineSpouseFullName = QtWidgets.QLineEdit(self.grpspouse)
        self.lineSpouseFullName.setEnabled(True)
        self.lineSpouseFullName.setObjectName("lineSpouseFullName")
        self.gridLayout_8.addWidget(self.lineSpouseFullName, 1, 0, 1, 1)
        self.lineSpouseAlias = QtWidgets.QLineEdit(self.grpspouse)
        self.lineSpouseAlias.setEnabled(True)
        self.lineSpouseAlias.setObjectName("lineSpouseAlias")
        self.gridLayout_8.addWidget(self.lineSpouseAlias, 1, 1, 1, 1)
        self.lineSpouseFullAddress = QtWidgets.QLineEdit(self.grpspouse)
        self.lineSpouseFullAddress.setEnabled(True)
        self.lineSpouseFullAddress.setObjectName("lineSpouseFullAddress")
        self.gridLayout_8.addWidget(self.lineSpouseFullAddress, 1, 2, 1, 1)
        self.lineSpouseEmployer = QtWidgets.QLineEdit(self.grpspouse)
        self.lineSpouseEmployer.setEnabled(True)
        self.lineSpouseEmployer.setObjectName("lineSpouseEmployer")
        self.gridLayout_8.addWidget(self.lineSpouseEmployer, 1, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.grpspouse)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 2, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.grpspouse)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 2, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.grpspouse)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 2, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.grpspouse)
        self.label_48.setObjectName("label_48")
        self.gridLayout_8.addWidget(self.label_48, 2, 3, 1, 1)
        self.dateSpouseDOB = QtWidgets.QDateEdit(self.grpspouse)
        self.dateSpouseDOB.setEnabled(True)
        self.dateSpouseDOB.setObjectName("dateSpouseDOB")
        self.gridLayout_8.addWidget(self.dateSpouseDOB, 3, 1, 1, 1)
        self.lineSpouseTRN = QtWidgets.QLineEdit(self.grpspouse)
        self.lineSpouseTRN.setEnabled(True)
        self.lineSpouseTRN.setObjectName("lineSpouseTRN")
        self.gridLayout_8.addWidget(self.lineSpouseTRN, 3, 3, 1, 1)
        self.lineSpouseTelNo = QtWidgets.QLineEdit(self.grpspouse)
        self.lineSpouseTelNo.setEnabled(True)
        self.lineSpouseTelNo.setObjectName("lineSpouseTelNo")
        self.gridLayout_8.addWidget(self.lineSpouseTelNo, 3, 2, 1, 1)
        self.lineSpouseIncome = QtWidgets.QLineEdit(self.grpspouse)
        self.lineSpouseIncome.setEnabled(True)
        self.lineSpouseIncome.setObjectName("lineSpouseIncome")
        self.gridLayout_8.addWidget(self.lineSpouseIncome, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.grpspouse)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem3)
        self.tabWidget.addTab(self.tabBorrower, "")
        self.tabGuarantor = QtWidgets.QWidget()
        self.tabGuarantor.setObjectName("tabGuarantor")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabGuarantor)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tabGuarantor)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 977, 995))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.grpGGeneralInformation = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpGGeneralInformation.sizePolicy().hasHeightForWidth())
        self.grpGGeneralInformation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grpGGeneralInformation.setFont(font)
        self.grpGGeneralInformation.setObjectName("grpGGeneralInformation")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.grpGGeneralInformation)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_71 = QtWidgets.QLabel(self.grpGGeneralInformation)
        self.label_71.setObjectName("label_71")
        self.gridLayout_13.addWidget(self.label_71, 0, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.grpGGeneralInformation)
        self.label_72.setObjectName("label_72")
        self.gridLayout_13.addWidget(self.label_72, 0, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.grpGGeneralInformation)
        self.label_73.setObjectName("label_73")
        self.gridLayout_13.addWidget(self.label_73, 0, 2, 1, 1)
        self.lineEditGMiddleInit = QtWidgets.QLineEdit(self.grpGGeneralInformation)
        self.lineEditGMiddleInit.setEnabled(True)
        self.lineEditGMiddleInit.setObjectName("lineEditGMiddleInit")
        self.gridLayout_13.addWidget(self.lineEditGMiddleInit, 1, 1, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.grpGGeneralInformation)
        self.label_74.setObjectName("label_74")
        self.gridLayout_13.addWidget(self.label_74, 0, 3, 1, 1)
        self.lineEditGFirstName = QtWidgets.QLineEdit(self.grpGGeneralInformation)
        self.lineEditGFirstName.setEnabled(True)
        self.lineEditGFirstName.setObjectName("lineEditGFirstName")
        self.gridLayout_13.addWidget(self.lineEditGFirstName, 1, 0, 1, 1)
        self.lineEditGLastName = QtWidgets.QLineEdit(self.grpGGeneralInformation)
        self.lineEditGLastName.setEnabled(True)
        self.lineEditGLastName.setObjectName("lineEditGLastName")
        self.gridLayout_13.addWidget(self.lineEditGLastName, 1, 2, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.grpGGeneralInformation)
        self.label_76.setObjectName("label_76")
        self.gridLayout_13.addWidget(self.label_76, 2, 1, 1, 1)
        self.lineEditGMiddleInit_2 = QtWidgets.QLineEdit(self.grpGGeneralInformation)
        self.lineEditGMiddleInit_2.setEnabled(True)
        self.lineEditGMiddleInit_2.setObjectName("lineEditGMiddleInit_2")
        self.gridLayout_13.addWidget(self.lineEditGMiddleInit_2, 1, 3, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.grpGGeneralInformation)
        self.label_75.setObjectName("label_75")
        self.gridLayout_13.addWidget(self.label_75, 2, 0, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.grpGGeneralInformation)
        self.label_78.setObjectName("label_78")
        self.gridLayout_13.addWidget(self.label_78, 2, 3, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.grpGGeneralInformation)
        self.label_77.setObjectName("label_77")
        self.gridLayout_13.addWidget(self.label_77, 2, 2, 1, 1)
        self.cboGSex = QtWidgets.QComboBox(self.grpGGeneralInformation)
        self.cboGSex.setEnabled(True)
        self.cboGSex.setObjectName("cboGSex")
        self.cboGSex.addItem("")
        self.cboGSex.addItem("")
        self.gridLayout_13.addWidget(self.cboGSex, 3, 0, 1, 1)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.grpGGeneralInformation)
        self.dateEdit_4.setEnabled(True)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.gridLayout_13.addWidget(self.dateEdit_4, 3, 1, 1, 1)
        self.cboGMaritalStatus = QtWidgets.QComboBox(self.grpGGeneralInformation)
        self.cboGMaritalStatus.setEnabled(True)
        self.cboGMaritalStatus.setObjectName("cboGMaritalStatus")
        self.cboGMaritalStatus.addItem("")
        self.cboGMaritalStatus.addItem("")
        self.cboGMaritalStatus.addItem("")
        self.gridLayout_13.addWidget(self.cboGMaritalStatus, 3, 2, 1, 1)
        self.lineEditGTRN = QtWidgets.QLineEdit(self.grpGGeneralInformation)
        self.lineEditGTRN.setEnabled(True)
        self.lineEditGTRN.setObjectName("lineEditGTRN")
        self.gridLayout_13.addWidget(self.lineEditGTRN, 3, 3, 1, 1)
        self.label_118 = QtWidgets.QLabel(self.grpGGeneralInformation)
        self.label_118.setObjectName("label_118")
        self.gridLayout_13.addWidget(self.label_118, 4, 0, 1, 1)
        self.cboGRelations = QtWidgets.QComboBox(self.grpGGeneralInformation)
        self.cboGRelations.setObjectName("cboGRelations")
        self.cboGRelations.addItem("")
        self.cboGRelations.addItem("")
        self.cboGRelations.addItem("")
        self.cboGRelations.addItem("")
        self.cboGRelations.addItem("")
        self.cboGRelations.addItem("")
        self.cboGRelations.addItem("")
        self.cboGRelations.addItem("")
        self.cboGRelations.addItem("")
        self.cboGRelations.addItem("")
        self.cboGRelations.addItem("")
        self.gridLayout_13.addWidget(self.cboGRelations, 5, 0, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.grpGGeneralInformation)
        self.label_119.setObjectName("label_119")
        self.gridLayout_13.addWidget(self.label_119, 4, 1, 1, 1)
        self.lineGOther = QtWidgets.QLineEdit(self.grpGGeneralInformation)
        self.lineGOther.setObjectName("lineGOther")
        self.gridLayout_13.addWidget(self.lineGOther, 5, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.grpGGeneralInformation)
        self.grpGAddress = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpGAddress.sizePolicy().hasHeightForWidth())
        self.grpGAddress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grpGAddress.setFont(font)
        self.grpGAddress.setObjectName("grpGAddress")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.grpGAddress)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_79 = QtWidgets.QLabel(self.grpGAddress)
        self.label_79.setObjectName("label_79")
        self.gridLayout_14.addWidget(self.label_79, 0, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.grpGAddress)
        self.label_80.setObjectName("label_80")
        self.gridLayout_14.addWidget(self.label_80, 0, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.grpGAddress)
        self.label_81.setObjectName("label_81")
        self.gridLayout_14.addWidget(self.label_81, 0, 2, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.grpGAddress)
        self.label_82.setObjectName("label_82")
        self.gridLayout_14.addWidget(self.label_82, 0, 3, 1, 1)
        self.lineGAddress1 = QtWidgets.QLineEdit(self.grpGAddress)
        self.lineGAddress1.setEnabled(True)
        self.lineGAddress1.setObjectName("lineGAddress1")
        self.gridLayout_14.addWidget(self.lineGAddress1, 1, 0, 1, 1)
        self.lineGAddress2 = QtWidgets.QLineEdit(self.grpGAddress)
        self.lineGAddress2.setEnabled(True)
        self.lineGAddress2.setObjectName("lineGAddress2")
        self.gridLayout_14.addWidget(self.lineGAddress2, 1, 1, 1, 1)
        self.lineGAddress3 = QtWidgets.QLineEdit(self.grpGAddress)
        self.lineGAddress3.setEnabled(True)
        self.lineGAddress3.setObjectName("lineGAddress3")
        self.gridLayout_14.addWidget(self.lineGAddress3, 1, 2, 1, 1)
        self.lineGPrevLengthOfStay_2 = QtWidgets.QLineEdit(self.grpGAddress)
        self.lineGPrevLengthOfStay_2.setEnabled(True)
        self.lineGPrevLengthOfStay_2.setObjectName("lineGPrevLengthOfStay_2")
        self.gridLayout_14.addWidget(self.lineGPrevLengthOfStay_2, 1, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.grpGAddress)
        self.grpGPrevAddress = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpGPrevAddress.sizePolicy().hasHeightForWidth())
        self.grpGPrevAddress.setSizePolicy(sizePolicy)
        self.grpGPrevAddress.setObjectName("grpGPrevAddress")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.grpGPrevAddress)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_83 = QtWidgets.QLabel(self.grpGPrevAddress)
        self.label_83.setObjectName("label_83")
        self.gridLayout_15.addWidget(self.label_83, 0, 0, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.grpGPrevAddress)
        self.label_84.setObjectName("label_84")
        self.gridLayout_15.addWidget(self.label_84, 0, 1, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.grpGPrevAddress)
        self.label_85.setObjectName("label_85")
        self.gridLayout_15.addWidget(self.label_85, 0, 2, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.grpGPrevAddress)
        self.label_86.setObjectName("label_86")
        self.gridLayout_15.addWidget(self.label_86, 0, 3, 1, 1)
        self.lineGPrevAddress1 = QtWidgets.QLineEdit(self.grpGPrevAddress)
        self.lineGPrevAddress1.setEnabled(True)
        self.lineGPrevAddress1.setObjectName("lineGPrevAddress1")
        self.gridLayout_15.addWidget(self.lineGPrevAddress1, 1, 0, 1, 1)
        self.lineGPrevAddress2 = QtWidgets.QLineEdit(self.grpGPrevAddress)
        self.lineGPrevAddress2.setEnabled(True)
        self.lineGPrevAddress2.setObjectName("lineGPrevAddress2")
        self.gridLayout_15.addWidget(self.lineGPrevAddress2, 1, 1, 1, 1)
        self.lineGPrevAddress3 = QtWidgets.QLineEdit(self.grpGPrevAddress)
        self.lineGPrevAddress3.setEnabled(True)
        self.lineGPrevAddress3.setObjectName("lineGPrevAddress3")
        self.gridLayout_15.addWidget(self.lineGPrevAddress3, 1, 2, 1, 1)
        self.lineGPrevLengthOfStay = QtWidgets.QLineEdit(self.grpGPrevAddress)
        self.lineGPrevLengthOfStay.setEnabled(True)
        self.lineGPrevLengthOfStay.setObjectName("lineGPrevLengthOfStay")
        self.gridLayout_15.addWidget(self.lineGPrevLengthOfStay, 1, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.grpGPrevAddress)
        self.grpGContacts = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpGContacts.sizePolicy().hasHeightForWidth())
        self.grpGContacts.setSizePolicy(sizePolicy)
        self.grpGContacts.setObjectName("grpGContacts")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.grpGContacts)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_87 = QtWidgets.QLabel(self.grpGContacts)
        self.label_87.setObjectName("label_87")
        self.gridLayout_16.addWidget(self.label_87, 0, 0, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.grpGContacts)
        self.label_88.setObjectName("label_88")
        self.gridLayout_16.addWidget(self.label_88, 0, 1, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.grpGContacts)
        self.label_89.setObjectName("label_89")
        self.gridLayout_16.addWidget(self.label_89, 0, 2, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.grpGContacts)
        self.label_90.setObjectName("label_90")
        self.gridLayout_16.addWidget(self.label_90, 0, 3, 1, 1)
        self.lineGHomeTel = QtWidgets.QLineEdit(self.grpGContacts)
        self.lineGHomeTel.setEnabled(True)
        self.lineGHomeTel.setObjectName("lineGHomeTel")
        self.gridLayout_16.addWidget(self.lineGHomeTel, 1, 0, 1, 1)
        self.lineGWorkTel = QtWidgets.QLineEdit(self.grpGContacts)
        self.lineGWorkTel.setEnabled(True)
        self.lineGWorkTel.setObjectName("lineGWorkTel")
        self.gridLayout_16.addWidget(self.lineGWorkTel, 1, 1, 1, 1)
        self.lineGCellNo1 = QtWidgets.QLineEdit(self.grpGContacts)
        self.lineGCellNo1.setEnabled(True)
        self.lineGCellNo1.setObjectName("lineGCellNo1")
        self.gridLayout_16.addWidget(self.lineGCellNo1, 1, 2, 1, 1)
        self.lineGCellNo2 = QtWidgets.QLineEdit(self.grpGContacts)
        self.lineGCellNo2.setEnabled(True)
        self.lineGCellNo2.setObjectName("lineGCellNo2")
        self.gridLayout_16.addWidget(self.lineGCellNo2, 1, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.grpGContacts)
        self.grpGPrevEmployment = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpGPrevEmployment.sizePolicy().hasHeightForWidth())
        self.grpGPrevEmployment.setSizePolicy(sizePolicy)
        self.grpGPrevEmployment.setObjectName("grpGPrevEmployment")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.grpGPrevEmployment)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_91 = QtWidgets.QLabel(self.grpGPrevEmployment)
        self.label_91.setObjectName("label_91")
        self.gridLayout_17.addWidget(self.label_91, 0, 0, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.grpGPrevEmployment)
        self.label_92.setObjectName("label_92")
        self.gridLayout_17.addWidget(self.label_92, 0, 1, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.grpGPrevEmployment)
        self.label_93.setObjectName("label_93")
        self.gridLayout_17.addWidget(self.label_93, 0, 2, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.grpGPrevEmployment)
        self.label_94.setObjectName("label_94")
        self.gridLayout_17.addWidget(self.label_94, 0, 3, 1, 1)
        self.linePrevEmployer_2 = QtWidgets.QLineEdit(self.grpGPrevEmployment)
        self.linePrevEmployer_2.setEnabled(True)
        self.linePrevEmployer_2.setText("")
        self.linePrevEmployer_2.setObjectName("linePrevEmployer_2")
        self.gridLayout_17.addWidget(self.linePrevEmployer_2, 1, 0, 1, 1)
        self.linePrevOccupation_2 = QtWidgets.QLineEdit(self.grpGPrevEmployment)
        self.linePrevOccupation_2.setEnabled(True)
        self.linePrevOccupation_2.setText("")
        self.linePrevOccupation_2.setObjectName("linePrevOccupation_2")
        self.gridLayout_17.addWidget(self.linePrevOccupation_2, 1, 1, 1, 1)
        self.datePrevEmpStartDate_2 = QtWidgets.QDateEdit(self.grpGPrevEmployment)
        self.datePrevEmpStartDate_2.setEnabled(True)
        self.datePrevEmpStartDate_2.setObjectName("datePrevEmpStartDate_2")
        self.gridLayout_17.addWidget(self.datePrevEmpStartDate_2, 1, 2, 1, 1)
        self.linePrevDepartment_2 = QtWidgets.QLineEdit(self.grpGPrevEmployment)
        self.linePrevDepartment_2.setEnabled(True)
        self.linePrevDepartment_2.setText("")
        self.linePrevDepartment_2.setObjectName("linePrevDepartment_2")
        self.gridLayout_17.addWidget(self.linePrevDepartment_2, 1, 3, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.grpGPrevEmployment)
        self.label_95.setObjectName("label_95")
        self.gridLayout_17.addWidget(self.label_95, 2, 0, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.grpGPrevEmployment)
        self.label_96.setObjectName("label_96")
        self.gridLayout_17.addWidget(self.label_96, 2, 1, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.grpGPrevEmployment)
        self.label_97.setObjectName("label_97")
        self.gridLayout_17.addWidget(self.label_97, 2, 2, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.grpGPrevEmployment)
        self.label_98.setObjectName("label_98")
        self.gridLayout_17.addWidget(self.label_98, 2, 3, 1, 1)
        self.linePrevEmpAddress1_2 = QtWidgets.QLineEdit(self.grpGPrevEmployment)
        self.linePrevEmpAddress1_2.setEnabled(True)
        self.linePrevEmpAddress1_2.setText("")
        self.linePrevEmpAddress1_2.setObjectName("linePrevEmpAddress1_2")
        self.gridLayout_17.addWidget(self.linePrevEmpAddress1_2, 3, 0, 1, 1)
        self.linePrevEmpAddress2_2 = QtWidgets.QLineEdit(self.grpGPrevEmployment)
        self.linePrevEmpAddress2_2.setEnabled(True)
        self.linePrevEmpAddress2_2.setText("")
        self.linePrevEmpAddress2_2.setObjectName("linePrevEmpAddress2_2")
        self.gridLayout_17.addWidget(self.linePrevEmpAddress2_2, 3, 1, 1, 1)
        self.linePrevEmpAddress3_2 = QtWidgets.QLineEdit(self.grpGPrevEmployment)
        self.linePrevEmpAddress3_2.setEnabled(True)
        self.linePrevEmpAddress3_2.setText("")
        self.linePrevEmpAddress3_2.setObjectName("linePrevEmpAddress3_2")
        self.gridLayout_17.addWidget(self.linePrevEmpAddress3_2, 3, 2, 1, 1)
        self.linePrevEmpTelNo_2 = QtWidgets.QLineEdit(self.grpGPrevEmployment)
        self.linePrevEmpTelNo_2.setEnabled(True)
        self.linePrevEmpTelNo_2.setText("")
        self.linePrevEmpTelNo_2.setObjectName("linePrevEmpTelNo_2")
        self.gridLayout_17.addWidget(self.linePrevEmpTelNo_2, 3, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.grpGPrevEmployment)
        self.grpGEmployment = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpGEmployment.sizePolicy().hasHeightForWidth())
        self.grpGEmployment.setSizePolicy(sizePolicy)
        self.grpGEmployment.setObjectName("grpGEmployment")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.grpGEmployment)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_99 = QtWidgets.QLabel(self.grpGEmployment)
        self.label_99.setObjectName("label_99")
        self.gridLayout_18.addWidget(self.label_99, 2, 0, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.grpGEmployment)
        self.label_100.setObjectName("label_100")
        self.gridLayout_18.addWidget(self.label_100, 2, 2, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.grpGEmployment)
        self.label_101.setObjectName("label_101")
        self.gridLayout_18.addWidget(self.label_101, 2, 3, 1, 1)
        self.lineGEmpAddress1 = QtWidgets.QLineEdit(self.grpGEmployment)
        self.lineGEmpAddress1.setEnabled(True)
        self.lineGEmpAddress1.setText("")
        self.lineGEmpAddress1.setObjectName("lineGEmpAddress1")
        self.gridLayout_18.addWidget(self.lineGEmpAddress1, 3, 0, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.grpGEmployment)
        self.label_102.setObjectName("label_102")
        self.gridLayout_18.addWidget(self.label_102, 2, 1, 1, 1)
        self.lineGEmpTelNo = QtWidgets.QLineEdit(self.grpGEmployment)
        self.lineGEmpTelNo.setEnabled(True)
        self.lineGEmpTelNo.setText("")
        self.lineGEmpTelNo.setObjectName("lineGEmpTelNo")
        self.gridLayout_18.addWidget(self.lineGEmpTelNo, 3, 3, 1, 1)
        self.lineGEmpAddress2 = QtWidgets.QLineEdit(self.grpGEmployment)
        self.lineGEmpAddress2.setEnabled(True)
        self.lineGEmpAddress2.setText("")
        self.lineGEmpAddress2.setObjectName("lineGEmpAddress2")
        self.gridLayout_18.addWidget(self.lineGEmpAddress2, 3, 1, 1, 1)
        self.lineGEmpAddress3 = QtWidgets.QLineEdit(self.grpGEmployment)
        self.lineGEmpAddress3.setEnabled(True)
        self.lineGEmpAddress3.setText("")
        self.lineGEmpAddress3.setObjectName("lineGEmpAddress3")
        self.gridLayout_18.addWidget(self.lineGEmpAddress3, 3, 2, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.grpGEmployment)
        self.label_103.setObjectName("label_103")
        self.gridLayout_18.addWidget(self.label_103, 4, 0, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.grpGEmployment)
        self.label_104.setObjectName("label_104")
        self.gridLayout_18.addWidget(self.label_104, 0, 0, 1, 1)
        self.lineGEmployer = QtWidgets.QLineEdit(self.grpGEmployment)
        self.lineGEmployer.setEnabled(True)
        self.lineGEmployer.setText("")
        self.lineGEmployer.setObjectName("lineGEmployer")
        self.gridLayout_18.addWidget(self.lineGEmployer, 1, 0, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.grpGEmployment)
        self.label_105.setObjectName("label_105")
        self.gridLayout_18.addWidget(self.label_105, 0, 1, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.grpGEmployment)
        self.label_106.setObjectName("label_106")
        self.gridLayout_18.addWidget(self.label_106, 0, 2, 1, 1)
        self.lineGOccupation = QtWidgets.QLineEdit(self.grpGEmployment)
        self.lineGOccupation.setEnabled(True)
        self.lineGOccupation.setText("")
        self.lineGOccupation.setObjectName("lineGOccupation")
        self.gridLayout_18.addWidget(self.lineGOccupation, 1, 1, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.grpGEmployment)
        self.label_107.setObjectName("label_107")
        self.gridLayout_18.addWidget(self.label_107, 0, 3, 1, 1)
        self.dateGEmpStartDate = QtWidgets.QDateEdit(self.grpGEmployment)
        self.dateGEmpStartDate.setEnabled(True)
        self.dateGEmpStartDate.setObjectName("dateGEmpStartDate")
        self.gridLayout_18.addWidget(self.dateGEmpStartDate, 1, 2, 1, 1)
        self.lineGDepartment = QtWidgets.QLineEdit(self.grpGEmployment)
        self.lineGDepartment.setEnabled(True)
        self.lineGDepartment.setText("")
        self.lineGDepartment.setObjectName("lineGDepartment")
        self.gridLayout_18.addWidget(self.lineGDepartment, 1, 3, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.grpGEmployment)
        self.label_108.setObjectName("label_108")
        self.gridLayout_18.addWidget(self.label_108, 4, 1, 1, 1)
        self.lineGEditSalaryAmount = QtWidgets.QLineEdit(self.grpGEmployment)
        self.lineGEditSalaryAmount.setEnabled(True)
        self.lineGEditSalaryAmount.setObjectName("lineGEditSalaryAmount")
        self.gridLayout_18.addWidget(self.lineGEditSalaryAmount, 5, 1, 1, 1)
        self.cboGPaymentPeriod = QtWidgets.QComboBox(self.grpGEmployment)
        self.cboGPaymentPeriod.setEnabled(True)
        self.cboGPaymentPeriod.setObjectName("cboGPaymentPeriod")
        self.cboGPaymentPeriod.addItem("")
        self.cboGPaymentPeriod.addItem("")
        self.cboGPaymentPeriod.addItem("")
        self.cboGPaymentPeriod.addItem("")
        self.gridLayout_18.addWidget(self.cboGPaymentPeriod, 5, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.grpGEmployment)
        self.grpGspouse = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpGspouse.sizePolicy().hasHeightForWidth())
        self.grpGspouse.setSizePolicy(sizePolicy)
        self.grpGspouse.setObjectName("grpGspouse")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.grpGspouse)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_109 = QtWidgets.QLabel(self.grpGspouse)
        self.label_109.setObjectName("label_109")
        self.gridLayout_19.addWidget(self.label_109, 0, 0, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.grpGspouse)
        self.label_110.setObjectName("label_110")
        self.gridLayout_19.addWidget(self.label_110, 0, 1, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.grpGspouse)
        self.label_111.setObjectName("label_111")
        self.gridLayout_19.addWidget(self.label_111, 0, 2, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.grpGspouse)
        self.label_112.setObjectName("label_112")
        self.gridLayout_19.addWidget(self.label_112, 0, 3, 1, 1)
        self.lineGEditFirstName = QtWidgets.QLineEdit(self.grpGspouse)
        self.lineGEditFirstName.setEnabled(True)
        self.lineGEditFirstName.setObjectName("lineGEditFirstName")
        self.gridLayout_19.addWidget(self.lineGEditFirstName, 1, 0, 1, 1)
        self.lineGEditMiddleInit = QtWidgets.QLineEdit(self.grpGspouse)
        self.lineGEditMiddleInit.setEnabled(True)
        self.lineGEditMiddleInit.setObjectName("lineGEditMiddleInit")
        self.gridLayout_19.addWidget(self.lineGEditMiddleInit, 1, 1, 1, 1)
        self.lineGEditLastName = QtWidgets.QLineEdit(self.grpGspouse)
        self.lineGEditLastName.setEnabled(True)
        self.lineGEditLastName.setObjectName("lineGEditLastName")
        self.gridLayout_19.addWidget(self.lineGEditLastName, 1, 2, 1, 1)
        self.lineGEditMiddleInit_2 = QtWidgets.QLineEdit(self.grpGspouse)
        self.lineGEditMiddleInit_2.setEnabled(True)
        self.lineGEditMiddleInit_2.setObjectName("lineGEditMiddleInit_2")
        self.gridLayout_19.addWidget(self.lineGEditMiddleInit_2, 1, 3, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.grpGspouse)
        self.label_113.setObjectName("label_113")
        self.gridLayout_19.addWidget(self.label_113, 2, 0, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.grpGspouse)
        self.label_114.setObjectName("label_114")
        self.gridLayout_19.addWidget(self.label_114, 2, 1, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.grpGspouse)
        self.label_115.setObjectName("label_115")
        self.gridLayout_19.addWidget(self.label_115, 2, 2, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.grpGspouse)
        self.label_116.setObjectName("label_116")
        self.gridLayout_19.addWidget(self.label_116, 2, 3, 1, 1)
        self.dateGSpouseDOB = QtWidgets.QDateEdit(self.grpGspouse)
        self.dateGSpouseDOB.setEnabled(True)
        self.dateGSpouseDOB.setObjectName("dateGSpouseDOB")
        self.gridLayout_19.addWidget(self.dateGSpouseDOB, 3, 1, 1, 1)
        self.lineGSpouseTRN = QtWidgets.QLineEdit(self.grpGspouse)
        self.lineGSpouseTRN.setEnabled(True)
        self.lineGSpouseTRN.setObjectName("lineGSpouseTRN")
        self.gridLayout_19.addWidget(self.lineGSpouseTRN, 3, 3, 1, 1)
        self.lineGSpouseTelNo = QtWidgets.QLineEdit(self.grpGspouse)
        self.lineGSpouseTelNo.setEnabled(True)
        self.lineGSpouseTelNo.setObjectName("lineGSpouseTelNo")
        self.gridLayout_19.addWidget(self.lineGSpouseTelNo, 3, 2, 1, 1)
        self.lineGSpouseIncome = QtWidgets.QLineEdit(self.grpGspouse)
        self.lineGSpouseIncome.setEnabled(True)
        self.lineGSpouseIncome.setObjectName("lineGSpouseIncome")
        self.gridLayout_19.addWidget(self.lineGSpouseIncome, 3, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.grpGspouse)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tabGuarantor, "")
        self.tabReference = QtWidgets.QWidget()
        self.tabReference.setObjectName("tabReference")
        self.layoutWidget1 = QtWidgets.QWidget(self.tabReference)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 1011, 427))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.grpReference2 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.grpReference2.setObjectName("grpReference2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.grpReference2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_56 = QtWidgets.QLabel(self.grpReference2)
        self.label_56.setObjectName("label_56")
        self.gridLayout_9.addWidget(self.label_56, 0, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.grpReference2)
        self.label_57.setObjectName("label_57")
        self.gridLayout_9.addWidget(self.label_57, 0, 1, 1, 1)
        self.txtName_2 = QtWidgets.QLineEdit(self.grpReference2)
        self.txtName_2.setEnabled(True)
        self.txtName_2.setObjectName("txtName_2")
        self.gridLayout_9.addWidget(self.txtName_2, 1, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.grpReference2)
        self.label_58.setObjectName("label_58")
        self.gridLayout_9.addWidget(self.label_58, 2, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.grpReference2)
        self.label_59.setObjectName("label_59")
        self.gridLayout_9.addWidget(self.label_59, 2, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.grpReference2)
        self.label_60.setObjectName("label_60")
        self.gridLayout_9.addWidget(self.label_60, 2, 2, 1, 1)
        self.txtHomeTelNo_2 = QtWidgets.QLineEdit(self.grpReference2)
        self.txtHomeTelNo_2.setEnabled(True)
        self.txtHomeTelNo_2.setObjectName("txtHomeTelNo_2")
        self.gridLayout_9.addWidget(self.txtHomeTelNo_2, 3, 0, 1, 1)
        self.txtWorkNo_2 = QtWidgets.QLineEdit(self.grpReference2)
        self.txtWorkNo_2.setEnabled(True)
        self.txtWorkNo_2.setObjectName("txtWorkNo_2")
        self.gridLayout_9.addWidget(self.txtWorkNo_2, 3, 1, 1, 1)
        self.txtRelationship_2 = QtWidgets.QLineEdit(self.grpReference2)
        self.txtRelationship_2.setEnabled(True)
        self.txtRelationship_2.setObjectName("txtRelationship_2")
        self.gridLayout_9.addWidget(self.txtRelationship_2, 3, 2, 1, 1)
        self.txtAddress_2 = QtWidgets.QLineEdit(self.grpReference2)
        self.txtAddress_2.setEnabled(True)
        self.txtAddress_2.setObjectName("txtAddress_2")
        self.gridLayout_9.addWidget(self.txtAddress_2, 1, 1, 1, 2)
        self.gridLayout_12.addWidget(self.grpReference2, 0, 2, 1, 1)
        self.grpReference1 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.grpReference1.setObjectName("grpReference1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.grpReference1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.grpReference1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.grpReference1)
        self.label_54.setObjectName("label_54")
        self.gridLayout_7.addWidget(self.label_54, 0, 1, 1, 1)
        self.txtName = QtWidgets.QLineEdit(self.grpReference1)
        self.txtName.setEnabled(True)
        self.txtName.setObjectName("txtName")
        self.gridLayout_7.addWidget(self.txtName, 1, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.grpReference1)
        self.label_52.setObjectName("label_52")
        self.gridLayout_7.addWidget(self.label_52, 2, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.grpReference1)
        self.label_53.setObjectName("label_53")
        self.gridLayout_7.addWidget(self.label_53, 2, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.grpReference1)
        self.label_55.setObjectName("label_55")
        self.gridLayout_7.addWidget(self.label_55, 2, 2, 1, 1)
        self.txtHomeTelNo = QtWidgets.QLineEdit(self.grpReference1)
        self.txtHomeTelNo.setEnabled(True)
        self.txtHomeTelNo.setObjectName("txtHomeTelNo")
        self.gridLayout_7.addWidget(self.txtHomeTelNo, 3, 0, 1, 1)
        self.txtWorkNo = QtWidgets.QLineEdit(self.grpReference1)
        self.txtWorkNo.setEnabled(True)
        self.txtWorkNo.setObjectName("txtWorkNo")
        self.gridLayout_7.addWidget(self.txtWorkNo, 3, 1, 1, 1)
        self.txtRelationship = QtWidgets.QLineEdit(self.grpReference1)
        self.txtRelationship.setEnabled(True)
        self.txtRelationship.setObjectName("txtRelationship")
        self.gridLayout_7.addWidget(self.txtRelationship, 3, 2, 1, 1)
        self.txtAddress = QtWidgets.QLineEdit(self.grpReference1)
        self.txtAddress.setEnabled(True)
        self.txtAddress.setObjectName("txtAddress")
        self.gridLayout_7.addWidget(self.txtAddress, 1, 1, 1, 2)
        self.gridLayout_12.addWidget(self.grpReference1, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem5, 0, 1, 1, 1)
        self.grpReference4 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.grpReference4.setObjectName("grpReference4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.grpReference4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_66 = QtWidgets.QLabel(self.grpReference4)
        self.label_66.setObjectName("label_66")
        self.gridLayout_11.addWidget(self.label_66, 0, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.grpReference4)
        self.label_67.setObjectName("label_67")
        self.gridLayout_11.addWidget(self.label_67, 0, 1, 1, 1)
        self.txtName_3 = QtWidgets.QLineEdit(self.grpReference4)
        self.txtName_3.setEnabled(True)
        self.txtName_3.setObjectName("txtName_3")
        self.gridLayout_11.addWidget(self.txtName_3, 1, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.grpReference4)
        self.label_68.setObjectName("label_68")
        self.gridLayout_11.addWidget(self.label_68, 2, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.grpReference4)
        self.label_69.setObjectName("label_69")
        self.gridLayout_11.addWidget(self.label_69, 2, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.grpReference4)
        self.label_70.setObjectName("label_70")
        self.gridLayout_11.addWidget(self.label_70, 2, 2, 1, 1)
        self.txtHomeTelNo_3 = QtWidgets.QLineEdit(self.grpReference4)
        self.txtHomeTelNo_3.setEnabled(True)
        self.txtHomeTelNo_3.setObjectName("txtHomeTelNo_3")
        self.gridLayout_11.addWidget(self.txtHomeTelNo_3, 3, 0, 1, 1)
        self.txtWorkNo_3 = QtWidgets.QLineEdit(self.grpReference4)
        self.txtWorkNo_3.setEnabled(True)
        self.txtWorkNo_3.setObjectName("txtWorkNo_3")
        self.gridLayout_11.addWidget(self.txtWorkNo_3, 3, 1, 1, 1)
        self.txtRelationship_3 = QtWidgets.QLineEdit(self.grpReference4)
        self.txtRelationship_3.setEnabled(True)
        self.txtRelationship_3.setObjectName("txtRelationship_3")
        self.gridLayout_11.addWidget(self.txtRelationship_3, 3, 2, 1, 1)
        self.txtAddress_3 = QtWidgets.QLineEdit(self.grpReference4)
        self.txtAddress_3.setEnabled(True)
        self.txtAddress_3.setObjectName("txtAddress_3")
        self.gridLayout_11.addWidget(self.txtAddress_3, 1, 1, 1, 2)
        self.gridLayout_12.addWidget(self.grpReference4, 2, 2, 1, 1)
        self.grpReference3 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.grpReference3.setEnabled(True)
        self.grpReference3.setObjectName("grpReference3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.grpReference3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_61 = QtWidgets.QLabel(self.grpReference3)
        self.label_61.setObjectName("label_61")
        self.gridLayout_10.addWidget(self.label_61, 0, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.grpReference3)
        self.label_62.setObjectName("label_62")
        self.gridLayout_10.addWidget(self.label_62, 0, 1, 1, 1)
        self.txtName_4 = QtWidgets.QLineEdit(self.grpReference3)
        self.txtName_4.setEnabled(True)
        self.txtName_4.setObjectName("txtName_4")
        self.gridLayout_10.addWidget(self.txtName_4, 1, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.grpReference3)
        self.label_63.setObjectName("label_63")
        self.gridLayout_10.addWidget(self.label_63, 2, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.grpReference3)
        self.label_64.setObjectName("label_64")
        self.gridLayout_10.addWidget(self.label_64, 2, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.grpReference3)
        self.label_65.setObjectName("label_65")
        self.gridLayout_10.addWidget(self.label_65, 2, 2, 1, 1)
        self.txtHomeTelNo_4 = QtWidgets.QLineEdit(self.grpReference3)
        self.txtHomeTelNo_4.setEnabled(True)
        self.txtHomeTelNo_4.setObjectName("txtHomeTelNo_4")
        self.gridLayout_10.addWidget(self.txtHomeTelNo_4, 3, 0, 1, 1)
        self.txtWorkNo_4 = QtWidgets.QLineEdit(self.grpReference3)
        self.txtWorkNo_4.setEnabled(True)
        self.txtWorkNo_4.setObjectName("txtWorkNo_4")
        self.gridLayout_10.addWidget(self.txtWorkNo_4, 3, 1, 1, 1)
        self.txtRelationship_4 = QtWidgets.QLineEdit(self.grpReference3)
        self.txtRelationship_4.setEnabled(True)
        self.txtRelationship_4.setObjectName("txtRelationship_4")
        self.gridLayout_10.addWidget(self.txtRelationship_4, 3, 2, 1, 1)
        self.txtAddress_4 = QtWidgets.QLineEdit(self.grpReference3)
        self.txtAddress_4.setEnabled(True)
        self.txtAddress_4.setObjectName("txtAddress_4")
        self.gridLayout_10.addWidget(self.txtAddress_4, 1, 1, 1, 2)
        self.gridLayout_12.addWidget(self.grpReference3, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabReference, "")
        self.tabAdditionalInfo = QtWidgets.QWidget()
        self.tabAdditionalInfo.setObjectName("tabAdditionalInfo")
        self.layoutWidget2 = QtWidgets.QWidget(self.tabAdditionalInfo)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 1021, 741))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lstAdditional = QtWidgets.QListView(self.layoutWidget2)
        self.lstAdditional.setEnabled(True)
        self.lstAdditional.setObjectName("lstAdditional")
        self.verticalLayout_5.addWidget(self.lstAdditional)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_51 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_2.addWidget(self.label_51)
        self.txtUpload = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txtUpload.setEnabled(True)
        self.txtUpload.setObjectName("txtUpload")
        self.horizontalLayout_2.addWidget(self.txtUpload)
        self.btnBrowser = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnBrowser.setEnabled(True)
        self.btnBrowser.setObjectName("btnBrowser")
        self.horizontalLayout_2.addWidget(self.btnBrowser)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.picAdditional = QtWidgets.QGraphicsView(self.layoutWidget2)
        self.picAdditional.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picAdditional.sizePolicy().hasHeightForWidth())
        self.picAdditional.setSizePolicy(sizePolicy)
        self.picAdditional.setMinimumSize(QtCore.QSize(700, 0))
        self.picAdditional.setObjectName("picAdditional")
        self.horizontalLayout_3.addWidget(self.picAdditional)
        self.tabWidget.addTab(self.tabAdditionalInfo, "")
        self.tabComment = QtWidgets.QWidget()
        self.tabComment.setObjectName("tabComment")
        self.layoutWidget3 = QtWidgets.QWidget(self.tabComment)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 30, 1011, 681))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tblComment = QtWidgets.QTableView(self.layoutWidget3)
        self.tblComment.setEnabled(True)
        self.tblComment.setObjectName("tblComment")
        self.verticalLayout_4.addWidget(self.tblComment)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblComment = QtWidgets.QLabel(self.layoutWidget3)
        self.lblComment.setObjectName("lblComment")
        self.horizontalLayout.addWidget(self.lblComment)
        self.lineComment = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineComment.setEnabled(True)
        self.lineComment.setObjectName("lineComment")
        self.horizontalLayout.addWidget(self.lineComment)
        self.btmSubmit = QtWidgets.QPushButton(self.layoutWidget3)
        self.btmSubmit.setEnabled(True)
        self.btmSubmit.setObjectName("btmSubmit")
        self.horizontalLayout.addWidget(self.btmSubmit)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabComment, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 700))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 231, 611))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.picBorrower = QtWidgets.QGraphicsView(self.layoutWidget4)
        self.picBorrower.setObjectName("picBorrower")
        self.verticalLayout.addWidget(self.picBorrower)
        self.btnBorrowerUpload = QtWidgets.QPushButton(self.layoutWidget4)
        self.btnBorrowerUpload.setObjectName("btnBorrowerUpload")
        self.verticalLayout.addWidget(self.btnBorrowerUpload)
        spacerItem8 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.picGuarantor = QtWidgets.QGraphicsView(self.layoutWidget4)
        self.picGuarantor.setObjectName("picGuarantor")
        self.verticalLayout.addWidget(self.picGuarantor)
        self.btnGuarantorUpload = QtWidgets.QPushButton(self.layoutWidget4)
        self.btnGuarantorUpload.setObjectName("btnGuarantorUpload")
        self.verticalLayout.addWidget(self.btnGuarantorUpload)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.actionApplied = QtWidgets.QAction(FormBorrower)
        self.actionApplied.setObjectName("actionApplied")

        self.retranslateUi(FormBorrower)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(FormBorrower)

    def retranslateUi(self, FormBorrower):
        _translate = QtCore.QCoreApplication.translate
        FormBorrower.setWindowTitle(_translate("FormBorrower", "Borrower"))
        self.btnApplied.setText(_translate("FormBorrower", "Applied"))
        self.btnEdit.setText(_translate("FormBorrower", "Edit"))
        self.btnDelete.setText(_translate("FormBorrower", "Delete"))
        self.btnSave.setText(_translate("FormBorrower", "Save"))
        self.btnCancel.setText(_translate("FormBorrower", "Cancel"))
        self.btnFind.setText(_translate("FormBorrower", "Find"))
        self.dockWidgetFindBorrower.setWindowTitle(_translate("FormBorrower", "Find Borrowers"))
        self.label_117.setText(_translate("FormBorrower", "Name"))
        self.lblID.setText(_translate("FormBorrower", "ID No"))
        self.lblDate.setText(_translate("FormBorrower", "Date"))
        self.label_5.setText(_translate("FormBorrower", "Borrowers Name"))
        self.grpGeneralInfomation.setTitle(_translate("FormBorrower", "General Information"))
        self.label.setText(_translate("FormBorrower", "First Name"))
        self.label_2.setText(_translate("FormBorrower", "Middle Init"))
        self.label_3.setText(_translate("FormBorrower", "Last Name"))
        self.label_6.setText(_translate("FormBorrower", "Alias"))
        self.label_7.setText(_translate("FormBorrower", "Sex"))
        self.label_8.setText(_translate("FormBorrower", "DOB"))
        self.label_9.setText(_translate("FormBorrower", "Marital Status"))
        self.label_14.setText(_translate("FormBorrower", "TRN"))
        self.cbosex.setCurrentText(_translate("FormBorrower", "Male"))
        self.cbosex.setItemText(0, _translate("FormBorrower", "Male"))
        self.cbosex.setItemText(1, _translate("FormBorrower", "Female"))
        self.cboMaritalStatus.setItemText(0, _translate("FormBorrower", "Single"))
        self.cboMaritalStatus.setItemText(1, _translate("FormBorrower", "Married"))
        self.cboMaritalStatus.setItemText(2, _translate("FormBorrower", "Divorced"))
        self.grpAddress.setTitle(_translate("FormBorrower", "Address"))
        self.label_10.setText(_translate("FormBorrower", "Address 1"))
        self.label_11.setText(_translate("FormBorrower", "Address 2"))
        self.label_12.setText(_translate("FormBorrower", "Address 3"))
        self.label_15.setText(_translate("FormBorrower", "Length of Stay"))
        self.grpPrevAddress.setTitle(_translate("FormBorrower", "Prev Address"))
        self.label_16.setText(_translate("FormBorrower", "Address 1"))
        self.label_17.setText(_translate("FormBorrower", "Address 2"))
        self.label_18.setText(_translate("FormBorrower", "Address 3"))
        self.label_20.setText(_translate("FormBorrower", "Length of Stay"))
        self.grpContacts.setTitle(_translate("FormBorrower", "Contacts"))
        self.label_21.setText(_translate("FormBorrower", "Home Telno"))
        self.label_22.setText(_translate("FormBorrower", "Work Telno"))
        self.label_23.setText(_translate("FormBorrower", "CellNo."))
        self.label_24.setText(_translate("FormBorrower", "CellNo 2"))
        self.grpPrevEmployment.setTitle(_translate("FormBorrower", "Previous Employment"))
        self.label_25.setText(_translate("FormBorrower", "Employer"))
        self.label_27.setText(_translate("FormBorrower", "Occupation"))
        self.label_31.setText(_translate("FormBorrower", "Start Date"))
        self.label_32.setText(_translate("FormBorrower", "Department"))
        self.label_26.setText(_translate("FormBorrower", "Address 1"))
        self.label_28.setText(_translate("FormBorrower", "Address 2"))
        self.label_29.setText(_translate("FormBorrower", "Address 3"))
        self.label_30.setText(_translate("FormBorrower", "Telephone No"))
        self.grpEmployment.setTitle(_translate("FormBorrower", "Current Employment"))
        self.label_37.setText(_translate("FormBorrower", "Address 1"))
        self.label_39.setText(_translate("FormBorrower", "Address 3"))
        self.label_40.setText(_translate("FormBorrower", "Telephone No"))
        self.label_38.setText(_translate("FormBorrower", "Address 2"))
        self.label_49.setText(_translate("FormBorrower", "Payment Period"))
        self.label_33.setText(_translate("FormBorrower", "Employer"))
        self.label_34.setText(_translate("FormBorrower", "Occupation"))
        self.label_35.setText(_translate("FormBorrower", "Start Date"))
        self.label_36.setText(_translate("FormBorrower", "Department"))
        self.label_50.setText(_translate("FormBorrower", "Salary Amount"))
        self.cboPaymentPeriod.setItemText(0, _translate("FormBorrower", "Weekly"))
        self.cboPaymentPeriod.setItemText(1, _translate("FormBorrower", "Forthnightly"))
        self.cboPaymentPeriod.setItemText(2, _translate("FormBorrower", "Monthly"))
        self.cboPaymentPeriod.setItemText(3, _translate("FormBorrower", "Adhoc"))
        self.grpspouse.setTitle(_translate("FormBorrower", "Spouse"))
        self.label_41.setText(_translate("FormBorrower", "FullName"))
        self.label_42.setText(_translate("FormBorrower", "Alias"))
        self.label_43.setText(_translate("FormBorrower", "Full Address"))
        self.label_44.setText(_translate("FormBorrower", "Employer"))
        self.label_45.setText(_translate("FormBorrower", "Income"))
        self.label_46.setText(_translate("FormBorrower", "DOB"))
        self.label_47.setText(_translate("FormBorrower", "Tel No"))
        self.label_48.setText(_translate("FormBorrower", "TRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBorrower), _translate("FormBorrower", "General Information"))
        self.grpGGeneralInformation.setTitle(_translate("FormBorrower", "Guarantor General Information"))
        self.label_71.setText(_translate("FormBorrower", "First Name"))
        self.label_72.setText(_translate("FormBorrower", "Middle Init"))
        self.label_73.setText(_translate("FormBorrower", "Last Name"))
        self.label_74.setText(_translate("FormBorrower", "Alias"))
        self.label_76.setText(_translate("FormBorrower", "DOB"))
        self.label_75.setText(_translate("FormBorrower", "Sex"))
        self.label_78.setText(_translate("FormBorrower", "TRN"))
        self.label_77.setText(_translate("FormBorrower", "Marital Status"))
        self.cboGSex.setItemText(0, _translate("FormBorrower", "Male"))
        self.cboGSex.setItemText(1, _translate("FormBorrower", "Female"))
        self.cboGMaritalStatus.setItemText(0, _translate("FormBorrower", "Single"))
        self.cboGMaritalStatus.setItemText(1, _translate("FormBorrower", "Married"))
        self.cboGMaritalStatus.setItemText(2, _translate("FormBorrower", "Divorced"))
        self.label_118.setText(_translate("FormBorrower", "Relations to Borrower"))
        self.cboGRelations.setItemText(0, _translate("FormBorrower", "Mother"))
        self.cboGRelations.setItemText(1, _translate("FormBorrower", "Father"))
        self.cboGRelations.setItemText(2, _translate("FormBorrower", "Sister"))
        self.cboGRelations.setItemText(3, _translate("FormBorrower", "Cousin"))
        self.cboGRelations.setItemText(4, _translate("FormBorrower", "Nephew"))
        self.cboGRelations.setItemText(5, _translate("FormBorrower", "Husband"))
        self.cboGRelations.setItemText(6, _translate("FormBorrower", "Wife"))
        self.cboGRelations.setItemText(7, _translate("FormBorrower", "Friend"))
        self.cboGRelations.setItemText(8, _translate("FormBorrower", "Co-Worker"))
        self.cboGRelations.setItemText(9, _translate("FormBorrower", "Employer"))
        self.cboGRelations.setItemText(10, _translate("FormBorrower", "Other"))
        self.label_119.setText(_translate("FormBorrower", "Other"))
        self.grpGAddress.setTitle(_translate("FormBorrower", "Address"))
        self.label_79.setText(_translate("FormBorrower", "Address 1"))
        self.label_80.setText(_translate("FormBorrower", "Address 2"))
        self.label_81.setText(_translate("FormBorrower", "Address 3"))
        self.label_82.setText(_translate("FormBorrower", "Length of Stay"))
        self.grpGPrevAddress.setTitle(_translate("FormBorrower", "Prev Address"))
        self.label_83.setText(_translate("FormBorrower", "Address 1"))
        self.label_84.setText(_translate("FormBorrower", "Address 2"))
        self.label_85.setText(_translate("FormBorrower", "Address 3"))
        self.label_86.setText(_translate("FormBorrower", "Length of Stay"))
        self.grpGContacts.setTitle(_translate("FormBorrower", "Contacts"))
        self.label_87.setText(_translate("FormBorrower", "Home Telno"))
        self.label_88.setText(_translate("FormBorrower", "Work Telno"))
        self.label_89.setText(_translate("FormBorrower", "CellNo."))
        self.label_90.setText(_translate("FormBorrower", "CellNo 2"))
        self.grpGPrevEmployment.setTitle(_translate("FormBorrower", "Previous Employment"))
        self.label_91.setText(_translate("FormBorrower", "Employer"))
        self.label_92.setText(_translate("FormBorrower", "Occupation"))
        self.label_93.setText(_translate("FormBorrower", "Start Date"))
        self.label_94.setText(_translate("FormBorrower", "Department"))
        self.label_95.setText(_translate("FormBorrower", "Address 1"))
        self.label_96.setText(_translate("FormBorrower", "Address 2"))
        self.label_97.setText(_translate("FormBorrower", "Address 3"))
        self.label_98.setText(_translate("FormBorrower", "Telephone No"))
        self.grpGEmployment.setTitle(_translate("FormBorrower", "Current Employment"))
        self.label_99.setText(_translate("FormBorrower", "Address 1"))
        self.label_100.setText(_translate("FormBorrower", "Address 3"))
        self.label_101.setText(_translate("FormBorrower", "Telephone No"))
        self.label_102.setText(_translate("FormBorrower", "Address 2"))
        self.label_103.setText(_translate("FormBorrower", "Payment Period"))
        self.label_104.setText(_translate("FormBorrower", "Employer"))
        self.label_105.setText(_translate("FormBorrower", "Occupation"))
        self.label_106.setText(_translate("FormBorrower", "Start Date"))
        self.label_107.setText(_translate("FormBorrower", "Department"))
        self.label_108.setText(_translate("FormBorrower", "Salary Amount"))
        self.cboGPaymentPeriod.setItemText(0, _translate("FormBorrower", "Weekly"))
        self.cboGPaymentPeriod.setItemText(1, _translate("FormBorrower", "Forthnightly"))
        self.cboGPaymentPeriod.setItemText(2, _translate("FormBorrower", "Monthly"))
        self.cboGPaymentPeriod.setItemText(3, _translate("FormBorrower", "Adhoc"))
        self.grpGspouse.setTitle(_translate("FormBorrower", "Spouse"))
        self.label_109.setText(_translate("FormBorrower", "FullName"))
        self.label_110.setText(_translate("FormBorrower", "Alias"))
        self.label_111.setText(_translate("FormBorrower", "Full Address"))
        self.label_112.setText(_translate("FormBorrower", "Employer"))
        self.label_113.setText(_translate("FormBorrower", "Income"))
        self.label_114.setText(_translate("FormBorrower", "DOB"))
        self.label_115.setText(_translate("FormBorrower", "Tel No"))
        self.label_116.setText(_translate("FormBorrower", "TRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGuarantor), _translate("FormBorrower", "Guarantor"))
        self.grpReference2.setTitle(_translate("FormBorrower", "Reference 2"))
        self.label_56.setText(_translate("FormBorrower", "Name"))
        self.label_57.setText(_translate("FormBorrower", "Address"))
        self.label_58.setText(_translate("FormBorrower", "Home TelNo"))
        self.label_59.setText(_translate("FormBorrower", "Work TelNo"))
        self.label_60.setText(_translate("FormBorrower", "Relationship"))
        self.grpReference1.setTitle(_translate("FormBorrower", "Reference 1"))
        self.label_4.setText(_translate("FormBorrower", "Name"))
        self.label_54.setText(_translate("FormBorrower", "Address"))
        self.label_52.setText(_translate("FormBorrower", "Home TelNo"))
        self.label_53.setText(_translate("FormBorrower", "Work TelNo"))
        self.label_55.setText(_translate("FormBorrower", "Relationship"))
        self.grpReference4.setTitle(_translate("FormBorrower", "Reference 4"))
        self.label_66.setText(_translate("FormBorrower", "Name"))
        self.label_67.setText(_translate("FormBorrower", "Address"))
        self.label_68.setText(_translate("FormBorrower", "Home TelNo"))
        self.label_69.setText(_translate("FormBorrower", "Work TelNo"))
        self.label_70.setText(_translate("FormBorrower", "Relationship"))
        self.grpReference3.setTitle(_translate("FormBorrower", "Reference 3"))
        self.label_61.setText(_translate("FormBorrower", "Name"))
        self.label_62.setText(_translate("FormBorrower", "Address"))
        self.label_63.setText(_translate("FormBorrower", "Home TelNo"))
        self.label_64.setText(_translate("FormBorrower", "Work TelNo"))
        self.label_65.setText(_translate("FormBorrower", "Relationship"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReference), _translate("FormBorrower", "Reference"))
        self.label_51.setText(_translate("FormBorrower", "Upload"))
        self.btnBrowser.setText(_translate("FormBorrower", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdditionalInfo), _translate("FormBorrower", "Additional Information"))
        self.lblComment.setText(_translate("FormBorrower", "Comments"))
        self.btmSubmit.setText(_translate("FormBorrower", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabComment), _translate("FormBorrower", "Comments"))
        self.groupBox.setTitle(_translate("FormBorrower", "Photo"))
        self.label_13.setText(_translate("FormBorrower", "Borrower"))
        self.btnBorrowerUpload.setText(_translate("FormBorrower", "Upload"))
        self.label_19.setText(_translate("FormBorrower", "Guarantor"))
        self.btnGuarantorUpload.setText(_translate("FormBorrower", "Upload"))
        self.actionApplied.setText(_translate("FormBorrower", "Applied"))

