# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'borrower.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormBorrower(object):
    def setupUi(self, FormBorrower):
        FormBorrower.setObjectName("FormBorrower")
        FormBorrower.resize(1338, 835)
        FormBorrower.setAutoFillBackground(False)
        self.lineEdit = QtWidgets.QLineEdit(FormBorrower)
        self.lineEdit.setGeometry(QtCore.QRect(82, 10, 141, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(FormBorrower)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 61, 16))
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QDateEdit(FormBorrower)
        self.dateEdit.setGeometry(QtCore.QRect(80, 40, 141, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(FormBorrower)
        self.label_5.setGeometry(QtCore.QRect(250, 10, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget = QtWidgets.QTabWidget(FormBorrower)
        self.tabWidget.setGeometry(QtCore.QRect(11, 91, 1071, 731))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabBorrower = QtWidgets.QWidget()
        self.tabBorrower.setObjectName("tabBorrower")
        self.scrollArea = QtWidgets.QScrollArea(self.tabBorrower)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 1041, 691))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1018, 943))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_12 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_12)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_12)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_12)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_12)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.lineEditFirstName = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEditFirstName.setObjectName("lineEditFirstName")
        self.gridLayout.addWidget(self.lineEditFirstName, 1, 0, 1, 1)
        self.lineEditMiddleInit = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEditMiddleInit.setObjectName("lineEditMiddleInit")
        self.gridLayout.addWidget(self.lineEditMiddleInit, 1, 1, 1, 1)
        self.lineEditLastName = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEditLastName.setObjectName("lineEditLastName")
        self.gridLayout.addWidget(self.lineEditLastName, 1, 2, 1, 1)
        self.lineEditMiddleInit_2 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEditMiddleInit_2.setObjectName("lineEditMiddleInit_2")
        self.gridLayout.addWidget(self.lineEditMiddleInit_2, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_12)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_12)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_12)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_12)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 3, 0, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox_12)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 3, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 3, 2, 1, 1)
        self.lineEditMiddleInit_3 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEditMiddleInit_3.setObjectName("lineEditMiddleInit_3")
        self.gridLayout.addWidget(self.lineEditMiddleInit_3, 3, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_12)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 3, 1, 1)
        self.lineAddress1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineAddress1.setObjectName("lineAddress1")
        self.gridLayout_2.addWidget(self.lineAddress1, 1, 0, 1, 1)
        self.lineAddress2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineAddress2.setObjectName("lineAddress2")
        self.gridLayout_2.addWidget(self.lineAddress2, 1, 1, 1, 1)
        self.lineAddress3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineAddress3.setObjectName("lineAddress3")
        self.gridLayout_2.addWidget(self.lineAddress3, 1, 2, 1, 1)
        self.lineLengthOfStay = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineLengthOfStay.setObjectName("lineLengthOfStay")
        self.gridLayout_2.addWidget(self.lineLengthOfStay, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 3, 1, 1)
        self.linePrevAddress1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.linePrevAddress1.setObjectName("linePrevAddress1")
        self.gridLayout_3.addWidget(self.linePrevAddress1, 1, 0, 1, 1)
        self.linePrevAddress2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.linePrevAddress2.setObjectName("linePrevAddress2")
        self.gridLayout_3.addWidget(self.linePrevAddress2, 1, 1, 1, 1)
        self.linePrevAddress3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.linePrevAddress3.setObjectName("linePrevAddress3")
        self.gridLayout_3.addWidget(self.linePrevAddress3, 1, 2, 1, 1)
        self.linePrevLengthOfStay = QtWidgets.QLineEdit(self.groupBox_3)
        self.linePrevLengthOfStay.setObjectName("linePrevLengthOfStay")
        self.gridLayout_3.addWidget(self.linePrevLengthOfStay, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 3, 1, 1)
        self.lineHomeTel = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineHomeTel.setObjectName("lineHomeTel")
        self.gridLayout_4.addWidget(self.lineHomeTel, 1, 0, 1, 1)
        self.lineWorkTel = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineWorkTel.setObjectName("lineWorkTel")
        self.gridLayout_4.addWidget(self.lineWorkTel, 1, 1, 1, 1)
        self.lineCellNo1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineCellNo1.setObjectName("lineCellNo1")
        self.gridLayout_4.addWidget(self.lineCellNo1, 1, 2, 1, 1)
        self.lineCellNo2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineCellNo2.setObjectName("lineCellNo2")
        self.gridLayout_4.addWidget(self.lineCellNo2, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 0, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 0, 3, 1, 1)
        self.linePrevEmployer = QtWidgets.QLineEdit(self.groupBox_5)
        self.linePrevEmployer.setText("")
        self.linePrevEmployer.setObjectName("linePrevEmployer")
        self.gridLayout_5.addWidget(self.linePrevEmployer, 1, 0, 1, 1)
        self.linePrevOccupation = QtWidgets.QLineEdit(self.groupBox_5)
        self.linePrevOccupation.setText("")
        self.linePrevOccupation.setObjectName("linePrevOccupation")
        self.gridLayout_5.addWidget(self.linePrevOccupation, 1, 1, 1, 1)
        self.datePrevEmpStartDate = QtWidgets.QDateEdit(self.groupBox_5)
        self.datePrevEmpStartDate.setObjectName("datePrevEmpStartDate")
        self.gridLayout_5.addWidget(self.datePrevEmpStartDate, 1, 2, 1, 1)
        self.linePrevDepartment = QtWidgets.QLineEdit(self.groupBox_5)
        self.linePrevDepartment.setText("")
        self.linePrevDepartment.setObjectName("linePrevDepartment")
        self.gridLayout_5.addWidget(self.linePrevDepartment, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 2, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 2, 3, 1, 1)
        self.linePrevEmpAddress1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.linePrevEmpAddress1.setText("")
        self.linePrevEmpAddress1.setObjectName("linePrevEmpAddress1")
        self.gridLayout_5.addWidget(self.linePrevEmpAddress1, 3, 0, 1, 1)
        self.linePrevEmpAddress2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.linePrevEmpAddress2.setText("")
        self.linePrevEmpAddress2.setObjectName("linePrevEmpAddress2")
        self.gridLayout_5.addWidget(self.linePrevEmpAddress2, 3, 1, 1, 1)
        self.linePrevEmpAddress3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.linePrevEmpAddress3.setText("")
        self.linePrevEmpAddress3.setObjectName("linePrevEmpAddress3")
        self.gridLayout_5.addWidget(self.linePrevEmpAddress3, 3, 2, 1, 1)
        self.linePrevEmpTelNo = QtWidgets.QLineEdit(self.groupBox_5)
        self.linePrevEmpTelNo.setText("")
        self.linePrevEmpTelNo.setObjectName("linePrevEmpTelNo")
        self.gridLayout_5.addWidget(self.linePrevEmpTelNo, 3, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_37 = QtWidgets.QLabel(self.groupBox_6)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 2, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 2, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_6)
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 2, 3, 1, 1)
        self.lineEmpAddress1 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEmpAddress1.setText("")
        self.lineEmpAddress1.setObjectName("lineEmpAddress1")
        self.gridLayout_6.addWidget(self.lineEmpAddress1, 3, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 2, 1, 1, 1)
        self.lineEmpTelNo = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEmpTelNo.setText("")
        self.lineEmpTelNo.setObjectName("lineEmpTelNo")
        self.gridLayout_6.addWidget(self.lineEmpTelNo, 3, 3, 1, 1)
        self.lineEmpAddress2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEmpAddress2.setText("")
        self.lineEmpAddress2.setObjectName("lineEmpAddress2")
        self.gridLayout_6.addWidget(self.lineEmpAddress2, 3, 1, 1, 1)
        self.lineEmpAddress3 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEmpAddress3.setText("")
        self.lineEmpAddress3.setObjectName("lineEmpAddress3")
        self.gridLayout_6.addWidget(self.lineEmpAddress3, 3, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_6)
        self.label_49.setObjectName("label_49")
        self.gridLayout_6.addWidget(self.label_49, 4, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_6)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 0, 0, 1, 1)
        self.lineEmployer = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEmployer.setText("")
        self.lineEmployer.setObjectName("lineEmployer")
        self.gridLayout_6.addWidget(self.lineEmployer, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 0, 2, 1, 1)
        self.lineOccupation = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineOccupation.setText("")
        self.lineOccupation.setObjectName("lineOccupation")
        self.gridLayout_6.addWidget(self.lineOccupation, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_6)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 0, 3, 1, 1)
        self.dateEmpStartDate = QtWidgets.QDateEdit(self.groupBox_6)
        self.dateEmpStartDate.setObjectName("dateEmpStartDate")
        self.gridLayout_6.addWidget(self.dateEmpStartDate, 1, 2, 1, 1)
        self.lineDepartment = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineDepartment.setText("")
        self.lineDepartment.setObjectName("lineDepartment")
        self.gridLayout_6.addWidget(self.lineDepartment, 1, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox_6)
        self.label_50.setObjectName("label_50")
        self.gridLayout_6.addWidget(self.label_50, 4, 1, 1, 1)
        self.lineEditSalaryAmount = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEditSalaryAmount.setObjectName("lineEditSalaryAmount")
        self.gridLayout_6.addWidget(self.lineEditSalaryAmount, 5, 1, 1, 1)
        self.cboPaymentPeriod = QtWidgets.QComboBox(self.groupBox_6)
        self.cboPaymentPeriod.setObjectName("cboPaymentPeriod")
        self.gridLayout_6.addWidget(self.cboPaymentPeriod, 5, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_13 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_41 = QtWidgets.QLabel(self.groupBox_13)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_13)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_13)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 0, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_13)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 0, 3, 1, 1)
        self.lineEditFirstName_2 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEditFirstName_2.setObjectName("lineEditFirstName_2")
        self.gridLayout_8.addWidget(self.lineEditFirstName_2, 1, 0, 1, 1)
        self.lineEditMiddleInit_4 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEditMiddleInit_4.setObjectName("lineEditMiddleInit_4")
        self.gridLayout_8.addWidget(self.lineEditMiddleInit_4, 1, 1, 1, 1)
        self.lineEditLastName_2 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEditLastName_2.setObjectName("lineEditLastName_2")
        self.gridLayout_8.addWidget(self.lineEditLastName_2, 1, 2, 1, 1)
        self.lineEditMiddleInit_5 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEditMiddleInit_5.setObjectName("lineEditMiddleInit_5")
        self.gridLayout_8.addWidget(self.lineEditMiddleInit_5, 1, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_13)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 2, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_13)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 2, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_13)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 2, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_13)
        self.label_48.setObjectName("label_48")
        self.gridLayout_8.addWidget(self.label_48, 2, 3, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_8.addWidget(self.comboBox_3, 3, 0, 1, 1)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.groupBox_13)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.gridLayout_8.addWidget(self.dateEdit_3, 3, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_8.addWidget(self.comboBox_4, 3, 2, 1, 1)
        self.lineEditMiddleInit_6 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEditMiddleInit_6.setObjectName("lineEditMiddleInit_6")
        self.gridLayout_8.addWidget(self.lineEditMiddleInit_6, 3, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_13)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tabBorrower, "")
        self.tabGuarantor = QtWidgets.QWidget()
        self.tabGuarantor.setObjectName("tabGuarantor")
        self.tabWidget.addTab(self.tabGuarantor, "")
        self.tabMescellanous = QtWidgets.QWidget()
        self.tabMescellanous.setObjectName("tabMescellanous")
        self.tabWidget.addTab(self.tabMescellanous, "")
        self.tabNotes = QtWidgets.QWidget()
        self.tabNotes.setObjectName("tabNotes")
        self.tabWidget.addTab(self.tabNotes, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox = QtWidgets.QGroupBox(FormBorrower)
        self.groupBox.setGeometry(QtCore.QRect(1090, 90, 250, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 700))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 231, 611))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.graphicsView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.layoutWidget)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout.addWidget(self.graphicsView_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(FormBorrower)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormBorrower)

    def retranslateUi(self, FormBorrower):
        _translate = QtCore.QCoreApplication.translate
        FormBorrower.setWindowTitle(_translate("FormBorrower", "Borrower"))
        self.label_4.setText(_translate("FormBorrower", "ID No"))
        self.label_5.setText(_translate("FormBorrower", "Borrowers Name"))
        self.groupBox_12.setTitle(_translate("FormBorrower", "General Information"))
        self.label.setText(_translate("FormBorrower", "First Name"))
        self.label_2.setText(_translate("FormBorrower", "Middle Init"))
        self.label_3.setText(_translate("FormBorrower", "Last Name"))
        self.label_6.setText(_translate("FormBorrower", "Alias"))
        self.label_7.setText(_translate("FormBorrower", "Sex"))
        self.label_8.setText(_translate("FormBorrower", "DOB"))
        self.label_9.setText(_translate("FormBorrower", "Marital Status"))
        self.label_14.setText(_translate("FormBorrower", "TRN"))
        self.groupBox_2.setTitle(_translate("FormBorrower", "Address"))
        self.label_10.setText(_translate("FormBorrower", "Address 1"))
        self.label_11.setText(_translate("FormBorrower", "Address 2"))
        self.label_12.setText(_translate("FormBorrower", "Address 3"))
        self.label_15.setText(_translate("FormBorrower", "Length of Stay"))
        self.groupBox_3.setTitle(_translate("FormBorrower", "Prev Address"))
        self.label_16.setText(_translate("FormBorrower", "Address 1"))
        self.label_17.setText(_translate("FormBorrower", "Address 2"))
        self.label_18.setText(_translate("FormBorrower", "Address 3"))
        self.label_20.setText(_translate("FormBorrower", "Length of Stay"))
        self.groupBox_4.setTitle(_translate("FormBorrower", "Contacts"))
        self.label_21.setText(_translate("FormBorrower", "Home Telno"))
        self.label_22.setText(_translate("FormBorrower", "Work Telno"))
        self.label_23.setText(_translate("FormBorrower", "CellNo."))
        self.label_24.setText(_translate("FormBorrower", "CellNo 2"))
        self.groupBox_5.setTitle(_translate("FormBorrower", "Previous Employment"))
        self.label_25.setText(_translate("FormBorrower", "Employer"))
        self.label_27.setText(_translate("FormBorrower", "Occupation"))
        self.label_31.setText(_translate("FormBorrower", "Start Date"))
        self.label_32.setText(_translate("FormBorrower", "Department"))
        self.label_26.setText(_translate("FormBorrower", "Address 1"))
        self.label_28.setText(_translate("FormBorrower", "Address 2"))
        self.label_29.setText(_translate("FormBorrower", "Address 3"))
        self.label_30.setText(_translate("FormBorrower", "Telephone No"))
        self.groupBox_6.setTitle(_translate("FormBorrower", "Current Employment"))
        self.label_37.setText(_translate("FormBorrower", "Address 1"))
        self.label_39.setText(_translate("FormBorrower", "Address 3"))
        self.label_40.setText(_translate("FormBorrower", "Telephone No"))
        self.label_38.setText(_translate("FormBorrower", "Address 2"))
        self.label_49.setText(_translate("FormBorrower", "Payment Period"))
        self.label_33.setText(_translate("FormBorrower", "Employer"))
        self.label_34.setText(_translate("FormBorrower", "Occupation"))
        self.label_35.setText(_translate("FormBorrower", "Start Date"))
        self.label_36.setText(_translate("FormBorrower", "Department"))
        self.label_50.setText(_translate("FormBorrower", "Salary Amount"))
        self.groupBox_13.setTitle(_translate("FormBorrower", "Spouse"))
        self.label_41.setText(_translate("FormBorrower", "FullName"))
        self.label_42.setText(_translate("FormBorrower", "Alias"))
        self.label_43.setText(_translate("FormBorrower", "Full Address"))
        self.label_44.setText(_translate("FormBorrower", "Employer"))
        self.label_45.setText(_translate("FormBorrower", "Sex"))
        self.label_46.setText(_translate("FormBorrower", "DOB"))
        self.label_47.setText(_translate("FormBorrower", "Tel No"))
        self.label_48.setText(_translate("FormBorrower", "TRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBorrower), _translate("FormBorrower", "General Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGuarantor), _translate("FormBorrower", "Reference"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMescellanous), _translate("FormBorrower", "Financial"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), _translate("FormBorrower", "Guarantor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FormBorrower", "Additional Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("FormBorrower", "Comments"))
        self.groupBox.setTitle(_translate("FormBorrower", "Photo"))
        self.label_13.setText(_translate("FormBorrower", "Borrower"))
        self.pushButton.setText(_translate("FormBorrower", "Upload"))
        self.label_19.setText(_translate("FormBorrower", "Guarantor"))
        self.pushButton_2.setText(_translate("FormBorrower", "Upload"))

