# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 830)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuBorrower = QtWidgets.QMenu(self.menubar)
        self.menuBorrower.setObjectName("menuBorrower")
        self.menuLoan = QtWidgets.QMenu(self.menubar)
        self.menuLoan.setObjectName("menuLoan")
        self.menuPayment = QtWidgets.QMenu(self.menubar)
        self.menuPayment.setObjectName("menuPayment")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuBorrowers = QtWidgets.QMenu(self.menuReports)
        self.menuBorrowers.setObjectName("menuBorrowers")
        self.menuPayments = QtWidgets.QMenu(self.menuReports)
        self.menuPayments.setObjectName("menuPayments")
        self.menuLoans = QtWidgets.QMenu(self.menuReports)
        self.menuLoans.setObjectName("menuLoans")
        self.menuCollection = QtWidgets.QMenu(self.menuReports)
        self.menuCollection.setObjectName("menuCollection")
        self.menuCollections = QtWidgets.QMenu(self.menubar)
        self.menuCollections.setObjectName("menuCollections")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCashEagle_Help = QtWidgets.QAction(MainWindow)
        self.actionCashEagle_Help.setObjectName("actionCashEagle_Help")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSecurity = QtWidgets.QAction(MainWindow)
        self.actionSecurity.setObjectName("actionSecurity")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionSecurity_2 = QtWidgets.QAction(MainWindow)
        self.actionSecurity_2.setObjectName("actionSecurity_2")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.action_Borrower = QtWidgets.QAction(MainWindow)
        self.action_Borrower.setObjectName("action_Borrower")
        self.actionLocate_Borrowers = QtWidgets.QAction(MainWindow)
        self.actionLocate_Borrowers.setObjectName("actionLocate_Borrowers")
        self.actionBorrowersList = QtWidgets.QAction(MainWindow)
        self.actionBorrowersList.setObjectName("actionBorrowersList")
        self.action_Loans = QtWidgets.QAction(MainWindow)
        self.action_Loans.setObjectName("action_Loans")
        self.actionLoan_Assess = QtWidgets.QAction(MainWindow)
        self.actionLoan_Assess.setObjectName("actionLoan_Assess")
        self.actionCredit_Check = QtWidgets.QAction(MainWindow)
        self.actionCredit_Check.setObjectName("actionCredit_Check")
        self.actionMake_Payment = QtWidgets.QAction(MainWindow)
        self.actionMake_Payment.setObjectName("actionMake_Payment")
        self.actionPayment_List = QtWidgets.QAction(MainWindow)
        self.actionPayment_List.setObjectName("actionPayment_List")
        self.actionList_All_Borrowers = QtWidgets.QAction(MainWindow)
        self.actionList_All_Borrowers.setObjectName("actionList_All_Borrowers")
        self.actionNew_Applied = QtWidgets.QAction(MainWindow)
        self.actionNew_Applied.setObjectName("actionNew_Applied")
        self.actionNew_Loan = QtWidgets.QAction(MainWindow)
        self.actionNew_Loan.setObjectName("actionNew_Loan")
        self.actionAging_Loan = QtWidgets.QAction(MainWindow)
        self.actionAging_Loan.setObjectName("actionAging_Loan")
        self.actionCompleted_Loan = QtWidgets.QAction(MainWindow)
        self.actionCompleted_Loan.setObjectName("actionCompleted_Loan")
        self.actionOverdue_Loan = QtWidgets.QAction(MainWindow)
        self.actionOverdue_Loan.setObjectName("actionOverdue_Loan")
        self.actionPayment_Due_Today = QtWidgets.QAction(MainWindow)
        self.actionPayment_Due_Today.setObjectName("actionPayment_Due_Today")
        self.actionPayment_Made = QtWidgets.QAction(MainWindow)
        self.actionPayment_Made.setObjectName("actionPayment_Made")
        self.actionPayment_Overdue = QtWidgets.QAction(MainWindow)
        self.actionPayment_Overdue.setObjectName("actionPayment_Overdue")
        self.actionCalls_Made = QtWidgets.QAction(MainWindow)
        self.actionCalls_Made.setObjectName("actionCalls_Made")
        self.actionOverdue_List = QtWidgets.QAction(MainWindow)
        self.actionOverdue_List.setObjectName("actionOverdue_List")
        self.actionCall_Logs = QtWidgets.QAction(MainWindow)
        self.actionCall_Logs.setObjectName("actionCall_Logs")
        self.actionApplicants = QtWidgets.QAction(MainWindow)
        self.actionApplicants.setObjectName("actionApplicants")
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionSecurity_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuHelp.addAction(self.actionCashEagle_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuBorrower.addAction(self.actionApplicants)
        self.menuBorrower.addSeparator()
        self.menuBorrower.addAction(self.action_Borrower)
        self.menuBorrower.addAction(self.actionBorrowersList)
        self.menuLoan.addAction(self.action_Loans)
        self.menuLoan.addAction(self.actionLoan_Assess)
        self.menuPayment.addAction(self.actionMake_Payment)
        self.menuPayment.addAction(self.actionPayment_List)
        self.menuBorrowers.addAction(self.actionList_All_Borrowers)
        self.menuBorrowers.addAction(self.actionNew_Applied)
        self.menuPayments.addAction(self.actionPayment_Due_Today)
        self.menuPayments.addAction(self.actionPayment_Made)
        self.menuPayments.addAction(self.actionPayment_Overdue)
        self.menuLoans.addSeparator()
        self.menuLoans.addSeparator()
        self.menuLoans.addAction(self.actionNew_Loan)
        self.menuLoans.addAction(self.actionAging_Loan)
        self.menuLoans.addAction(self.actionCompleted_Loan)
        self.menuLoans.addAction(self.actionOverdue_Loan)
        self.menuCollection.addAction(self.actionCalls_Made)
        self.menuReports.addAction(self.menuBorrowers.menuAction())
        self.menuReports.addAction(self.menuLoans.menuAction())
        self.menuReports.addAction(self.menuPayments.menuAction())
        self.menuReports.addAction(self.menuCollection.menuAction())
        self.menuCollections.addAction(self.actionOverdue_List)
        self.menuCollections.addAction(self.actionCall_Logs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBorrower.menuAction())
        self.menubar.addAction(self.menuLoan.menuAction())
        self.menubar.addAction(self.menuPayment.menuAction())
        self.menubar.addAction(self.menuCollections.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Borrower)
        self.toolBar.addAction(self.action_Loans)
        self.toolBar.addAction(self.actionMake_Payment)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CashEagle"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuBorrower.setTitle(_translate("MainWindow", "Clients"))
        self.menuLoan.setTitle(_translate("MainWindow", "Loan"))
        self.menuPayment.setTitle(_translate("MainWindow", "Payment"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.menuBorrowers.setTitle(_translate("MainWindow", "Borrowers"))
        self.menuPayments.setTitle(_translate("MainWindow", "Payments"))
        self.menuLoans.setTitle(_translate("MainWindow", "Loans"))
        self.menuCollection.setTitle(_translate("MainWindow", "Collection"))
        self.menuCollections.setTitle(_translate("MainWindow", "Collections"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCashEagle_Help.setText(_translate("MainWindow", "CashEagle Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Alt+F"))
        self.actionSecurity.setText(_translate("MainWindow", "Security"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSecurity_2.setText(_translate("MainWindow", "Security"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.action_Borrower.setText(_translate("MainWindow", "Borrowers"))
        self.action_Borrower.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionLocate_Borrowers.setText(_translate("MainWindow", "Locate Borrowers"))
        self.actionBorrowersList.setText(_translate("MainWindow", "List"))
        self.action_Loans.setText(_translate("MainWindow", "Loans"))
        self.actionLoan_Assess.setText(_translate("MainWindow", "Loan Assess"))
        self.actionCredit_Check.setText(_translate("MainWindow", "Credit Check"))
        self.actionMake_Payment.setText(_translate("MainWindow", "Make Payment"))
        self.actionPayment_List.setText(_translate("MainWindow", "Payment List"))
        self.actionList_All_Borrowers.setText(_translate("MainWindow", "List All Borrowers"))
        self.actionNew_Applied.setText(_translate("MainWindow", "New Applied"))
        self.actionNew_Loan.setText(_translate("MainWindow", "New Loan"))
        self.actionAging_Loan.setText(_translate("MainWindow", "Aging Loan"))
        self.actionCompleted_Loan.setText(_translate("MainWindow", "Completed Loan"))
        self.actionOverdue_Loan.setText(_translate("MainWindow", "Overdue Loan"))
        self.actionPayment_Due_Today.setText(_translate("MainWindow", "Payment Due Today"))
        self.actionPayment_Made.setText(_translate("MainWindow", "Payment Made"))
        self.actionPayment_Overdue.setText(_translate("MainWindow", "Payment Overdue"))
        self.actionCalls_Made.setText(_translate("MainWindow", "Calls Made"))
        self.actionOverdue_List.setText(_translate("MainWindow", "Overdue List"))
        self.actionCall_Logs.setText(_translate("MainWindow", "Call Logs"))
        self.actionApplicants.setText(_translate("MainWindow", "Applicants"))

