# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 662)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuBorrower = QtWidgets.QMenu(self.menubar)
        self.menuBorrower.setObjectName("menuBorrower")
        self.menuLoan = QtWidgets.QMenu(self.menubar)
        self.menuLoan.setObjectName("menuLoan")
        self.menuPayment = QtWidgets.QMenu(self.menubar)
        self.menuPayment.setObjectName("menuPayment")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCashEagle_Help = QtWidgets.QAction(MainWindow)
        self.actionCashEagle_Help.setObjectName("actionCashEagle_Help")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSecurity = QtWidgets.QAction(MainWindow)
        self.actionSecurity.setObjectName("actionSecurity")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionSecurity_2 = QtWidgets.QAction(MainWindow)
        self.actionSecurity_2.setObjectName("actionSecurity_2")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionNew_Borrower = QtWidgets.QAction(MainWindow)
        self.actionNew_Borrower.setObjectName("actionNew_Borrower")
        self.actionLocate_Borrowers = QtWidgets.QAction(MainWindow)
        self.actionLocate_Borrowers.setObjectName("actionLocate_Borrowers")
        self.actionCheck_Borrowers = QtWidgets.QAction(MainWindow)
        self.actionCheck_Borrowers.setObjectName("actionCheck_Borrowers")
        self.actionNew_Loans = QtWidgets.QAction(MainWindow)
        self.actionNew_Loans.setObjectName("actionNew_Loans")
        self.actionLoan_Assess = QtWidgets.QAction(MainWindow)
        self.actionLoan_Assess.setObjectName("actionLoan_Assess")
        self.actionCredit_Check = QtWidgets.QAction(MainWindow)
        self.actionCredit_Check.setObjectName("actionCredit_Check")
        self.actionMake_Payment = QtWidgets.QAction(MainWindow)
        self.actionMake_Payment.setObjectName("actionMake_Payment")
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionSecurity_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuHelp.addAction(self.actionCashEagle_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuBorrower.addAction(self.actionNew_Borrower)
        self.menuBorrower.addAction(self.actionLocate_Borrowers)
        self.menuBorrower.addAction(self.actionCheck_Borrowers)
        self.menuBorrower.addSeparator()
        self.menuBorrower.addAction(self.actionCredit_Check)
        self.menuLoan.addAction(self.actionNew_Loans)
        self.menuLoan.addAction(self.actionLoan_Assess)
        self.menuPayment.addAction(self.actionMake_Payment)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBorrower.menuAction())
        self.menubar.addAction(self.menuLoan.menuAction())
        self.menubar.addAction(self.menuPayment.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CashEagle"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuBorrower.setTitle(_translate("MainWindow", "Borrower"))
        self.menuLoan.setTitle(_translate("MainWindow", "Loan"))
        self.menuPayment.setTitle(_translate("MainWindow", "Payment"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.actionCashEagle_Help.setText(_translate("MainWindow", "CashEagle Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Alt+F"))
        self.actionSecurity.setText(_translate("MainWindow", "Security"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSecurity_2.setText(_translate("MainWindow", "Security"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionNew_Borrower.setText(_translate("MainWindow", "New Borrower"))
        self.actionLocate_Borrowers.setText(_translate("MainWindow", "Locate Borrowers"))
        self.actionCheck_Borrowers.setText(_translate("MainWindow", "Borrower List"))
        self.actionNew_Loans.setText(_translate("MainWindow", "New Loans"))
        self.actionLoan_Assess.setText(_translate("MainWindow", "Loan Assess"))
        self.actionCredit_Check.setText(_translate("MainWindow", "Credit Check"))
        self.actionMake_Payment.setText(_translate("MainWindow", "Make Payment"))

